# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawDepositClient, RawDepositClient
from .types.create_new_address_request_type import CreateNewAddressRequestType
from .types.create_new_address_response import CreateNewAddressResponse
from .types.get_deposit_address_response import GetDepositAddressResponse
from .types.get_fiat_deposit_url_request_customer import GetFiatDepositUrlRequestCustomer
from .types.get_fiat_deposit_url_response import GetFiatDepositUrlResponse
from .types.refund_deposit_response import RefundDepositResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DepositClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDepositClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDepositClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDepositClient
        """
        return self._raw_client

    def get_deposit_address(
        self,
        *,
        ticker: str,
        request: str,
        nonce: str,
        network: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetDepositAddressResponse:
        """
        The endpoint retrieves a deposit address of the cryptocurrency.

        <Accordion title="Errors">
        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "ticker": ["The selected ticker is invalid."]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "network": ["The selected network is invalid."]
          }
        }
        ```

        ```json
        {
          "code": 1,
          "message": "Inner validation failed",
          "errors": {
            "ticker": ["Currency is not depositable"]
          }
        }
        ```
        </Accordion>

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        ticker : str
            Currencies ticker. Example: BTC ⚠️ Currency [ticker](/glossary#ticker) should not be [fiat](/glossary#fiat) and it’s “can_deposit” status must be “true”. See [Asset Status endpoint](/public/http-v4/asset-status-list) response for the status.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        network : typing.Optional[str]
            Cryptocurrency network. ⚠️ If currency has multiple networks like USDT, specify the network to use. See [ticker](/glossary#ticker) networks list in “networks” field from response [Asset Status endpoint](/public/http-v4/asset-status-list).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDepositAddressResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.deposit.get_deposit_address(ticker='BTC', request='{{request}}', nonce='{{nonce}}', )
        """
        _response = self._raw_client.get_deposit_address(
            ticker=ticker, request=request, nonce=nonce, network=network, request_options=request_options
        )
        return _response.data

    def get_fiat_deposit_url(
        self,
        *,
        ticker: str,
        provider: str,
        amount: str,
        request: str,
        nonce: str,
        unique_id: typing.Optional[str] = OMIT,
        customer: typing.Optional[GetFiatDepositUrlRequestCustomer] = OMIT,
        success_link: typing.Optional[str] = OMIT,
        failure_link: typing.Optional[str] = OMIT,
        return_link: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetFiatDepositUrlResponse:
        """
        The endpoint retrieves a deposit url of the [fiat](/glossary#fiat) invoice.

        The endpoint works on demand. Contact WhiteBIT support and provide the API key to get access to the functionality.

        <Accordion title="Errors">
        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "amount": ["Amount is too little for deposit"]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "provider": ["Cannot find currency for specified provider"]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "uniqueId": ["The unique id has already been taken."]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "amount": ["The amount must be a number."],
            "provider": ["The selected provider is invalid."],
            "ticker": ["The selected ticker is invalid."]
          }
        }
        ```

        ```json
        {
          "code": 10,
          "message": "Failed to generate deposit url"
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "amount": ["The amount field is required."],
            "provider": ["The provider field is required."],
            "ticker": ["The ticker field is required."],
            "uniqueId": ["The unique id field is required."]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "successLink": [
              "Your domain is incorrect. Please contact support for more details"
            ],
            "failureLink": [
              "Your domain is incorrect. Please contact support for more details"
            ]
          }
        }
        ```

        ```json
        {
          "success": false,
          "message": "You don't have permission to use this endpoint. Please contact support for more details",
          "code": 0
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "successLink": ["Uri domain must have only https scheme"],
            "failureLink": ["Uri domain must have only https scheme"]
          }
        }
        ```
        </Accordion>

        <Warning>
        When using VISAMASTER as [provider](/glossary#provider), pass the [referer header](https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Referer) when opening the invoice link (e.g. when opening https://someaddress.com). If the header is missing (e.g. when opening the link from a Telegram message), the browser is redirected to the WhiteBIT homepage
        </Warning>

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's [ticker](/glossary#ticker) ([fiat](/glossary#fiat)). ⚠️ Currencies ticker should be fiat and has "can_deposit" status must be "true". Use [Asset Status endpoint](/public/http-v4/asset-status-list) to know more about currency.

        provider : str
            [Fiat](/glossary#fiat) currency [provider](/glossary#provider). ⚠️ Currency provider should be taken from [Asset Status endpoint](/public/http-v4/asset-status-list) response.

        amount : str
            Deposit amount

        request : str
            Request signature

        nonce : str
            Unique request identifier

        unique_id : typing.Optional[str]
            Unique transaction identifier on client's side

        customer : typing.Optional[GetFiatDepositUrlRequestCustomer]
            Customer information (required for USD/EUR with VISAMASTER [provider](/glossary#provider))

        success_link : typing.Optional[str]
            Customer will be redirected to this URL by acquiring [provider](/glossary#provider) after success deposit. To activate this feature, please contact support

        failure_link : typing.Optional[str]
            Customer will be redirected to this URL in case of fail or rejection on acquiring provider side. To activate this feature, please contact support

        return_link : typing.Optional[str]
            Customer will be redirected to the URL defined if selects 'back' option after from the payment success or failure page. To activate this feature, define desired link. If not populated, option 'back' won't be displayed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFiatDepositUrlResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.deposit.get_fiat_deposit_url(ticker='UAH', provider='VISAMASTER', amount='100', unique_id='{{generateID}}', request='{{request}}', nonce='{{nonce}}', )
        """
        _response = self._raw_client.get_fiat_deposit_url(
            ticker=ticker,
            provider=provider,
            amount=amount,
            request=request,
            nonce=nonce,
            unique_id=unique_id,
            customer=customer,
            success_link=success_link,
            failure_link=failure_link,
            return_link=return_link,
            request_options=request_options,
        )
        return _response.data

    def issue_card_token(self, *, card_number: str, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        The endpoint issues a [card token](/glossary#card-token) for the specified card number.

        **Request Headers:**
        - `Authorization`: JWT token from the [Issue JWT token](/private/http-main-v4/issue-jwt-token) response field `data.token` (**Required**)
        - `Content-Type`: `application/json` (**Required**)

        Use the `data.token` value returned by [Issue JWT token](/private/http-main-v4/issue-jwt-token) as the `Authorization` header when calling this Fiat Gateway endpoint.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        card_number : str
            Target card number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.deposit.issue_card_token(card_number='4111111111111111', )
        """
        _response = self._raw_client.issue_card_token(card_number=card_number, request_options=request_options)
        return _response.data

    def refund_deposit(
        self,
        *,
        address: str,
        request: str,
        nonce: str,
        transaction_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RefundDepositResponse:
        """
        Refund a deposit.

        The system processes refunds only for deposits with status `canceled`.

        Obtain `transactionId` from the `deposit.canceled` webhook (`uniqueId`) or from the deposit/withdraw history in the WhiteBIT interface after support confirms refund availability.

        The refund address must support the same network and asset as the original deposit. The refund address must not be a WhiteBIT address. The refund address can differ from the original deposit sender address.

        <Accordion title="Errors">
        ```json
        {
          "code": 0,
          "message": "Transaction not refundable"
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "transactionId": ["The transaction id field is required."],
            "address": ["The address field is required."]
          }
        }
        ```
        </Accordion>

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        <Note>
        Refund processing does not complete instantly. Use the [refund.successful](/platform/webhook#whitebit-refund-successful) and [refund.failed](/platform/webhook#whitebit-refund-failed) webhooks to receive refund status updates.
        </Note>

        Parameters
        ----------
        address : str
            Destination wallet address for the refund. The address must support the same network and asset as the original deposit. Cannot be a WhiteBIT address. Does not have to match the original deposit address.

        request : str
            Base64-encoded request body. See the [authentication guide](/private/http-auth) for signature generation details.

        nonce : str
            A unique identifier for the request. Use a monotonically increasing value such as a Unix timestamp in milliseconds.

        transaction_id : typing.Optional[str]
            Transaction UUID of the deposit. Obtain from the [deposit.canceled](/platform/webhook) webhook (`uniqueId` field) or from the deposit/withdraw history in the WhiteBIT interface.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RefundDepositResponse
            System accepts refund request

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.deposit.refund_deposit(transaction_id='54bffeb7-7a8f-43f8-bcd8-f14ec10fee85', address='0x1234567890abcdef1234567890abcdef12345678', request='{{request}}', nonce='{{nonce}}', )
        """
        _response = self._raw_client.refund_deposit(
            address=address,
            request=request,
            nonce=nonce,
            transaction_id=transaction_id,
            request_options=request_options,
        )
        return _response.data

    def create_new_address(
        self,
        *,
        ticker: str,
        request: str,
        nonce: str,
        network: typing.Optional[str] = OMIT,
        type: typing.Optional[CreateNewAddressRequestType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateNewAddressResponse:
        """
        The endpoint creates a new address even when the last created address is not used. The endpoint is not available by default, contact support@whitebit.com to get permissions to use the endpoint.

        **Address types:**

        | Currency | Types               | Default |
        |----------|---------------------|---------|
        | BTC      | p2sh-segwit, bech32 | bech32  |
        | LTC      | p2sh-segwit, bech32 | bech32  |

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's ticker.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        network : typing.Optional[str]
            Currency's network (for multinetwork currencies). Example: OMNI or TRC20 or ERC20. For USDT default network is ERC20(ETH).

        type : typing.Optional[CreateNewAddressRequestType]
            Address type, available for specific currencies list (see address types table in endpoint description)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateNewAddressResponse
            All validations succeeded and creating transaction is started

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.deposit.create_new_address(ticker='XLM', request='{{request}}', nonce='{{nonce}}', )
        """
        _response = self._raw_client.create_new_address(
            ticker=ticker, request=request, nonce=nonce, network=network, type=type, request_options=request_options
        )
        return _response.data


class AsyncDepositClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDepositClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDepositClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDepositClient
        """
        return self._raw_client

    async def get_deposit_address(
        self,
        *,
        ticker: str,
        request: str,
        nonce: str,
        network: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetDepositAddressResponse:
        """
        The endpoint retrieves a deposit address of the cryptocurrency.

        <Accordion title="Errors">
        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "ticker": ["The selected ticker is invalid."]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "network": ["The selected network is invalid."]
          }
        }
        ```

        ```json
        {
          "code": 1,
          "message": "Inner validation failed",
          "errors": {
            "ticker": ["Currency is not depositable"]
          }
        }
        ```
        </Accordion>

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        ticker : str
            Currencies ticker. Example: BTC ⚠️ Currency [ticker](/glossary#ticker) should not be [fiat](/glossary#fiat) and it’s “can_deposit” status must be “true”. See [Asset Status endpoint](/public/http-v4/asset-status-list) response for the status.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        network : typing.Optional[str]
            Cryptocurrency network. ⚠️ If currency has multiple networks like USDT, specify the network to use. See [ticker](/glossary#ticker) networks list in “networks” field from response [Asset Status endpoint](/public/http-v4/asset-status-list).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDepositAddressResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.deposit.get_deposit_address(ticker='BTC', request='{{request}}', nonce='{{nonce}}', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_deposit_address(
            ticker=ticker, request=request, nonce=nonce, network=network, request_options=request_options
        )
        return _response.data

    async def get_fiat_deposit_url(
        self,
        *,
        ticker: str,
        provider: str,
        amount: str,
        request: str,
        nonce: str,
        unique_id: typing.Optional[str] = OMIT,
        customer: typing.Optional[GetFiatDepositUrlRequestCustomer] = OMIT,
        success_link: typing.Optional[str] = OMIT,
        failure_link: typing.Optional[str] = OMIT,
        return_link: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetFiatDepositUrlResponse:
        """
        The endpoint retrieves a deposit url of the [fiat](/glossary#fiat) invoice.

        The endpoint works on demand. Contact WhiteBIT support and provide the API key to get access to the functionality.

        <Accordion title="Errors">
        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "amount": ["Amount is too little for deposit"]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "provider": ["Cannot find currency for specified provider"]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "uniqueId": ["The unique id has already been taken."]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "amount": ["The amount must be a number."],
            "provider": ["The selected provider is invalid."],
            "ticker": ["The selected ticker is invalid."]
          }
        }
        ```

        ```json
        {
          "code": 10,
          "message": "Failed to generate deposit url"
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "amount": ["The amount field is required."],
            "provider": ["The provider field is required."],
            "ticker": ["The ticker field is required."],
            "uniqueId": ["The unique id field is required."]
          }
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "successLink": [
              "Your domain is incorrect. Please contact support for more details"
            ],
            "failureLink": [
              "Your domain is incorrect. Please contact support for more details"
            ]
          }
        }
        ```

        ```json
        {
          "success": false,
          "message": "You don't have permission to use this endpoint. Please contact support for more details",
          "code": 0
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "successLink": ["Uri domain must have only https scheme"],
            "failureLink": ["Uri domain must have only https scheme"]
          }
        }
        ```
        </Accordion>

        <Warning>
        When using VISAMASTER as [provider](/glossary#provider), pass the [referer header](https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Referer) when opening the invoice link (e.g. when opening https://someaddress.com). If the header is missing (e.g. when opening the link from a Telegram message), the browser is redirected to the WhiteBIT homepage
        </Warning>

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's [ticker](/glossary#ticker) ([fiat](/glossary#fiat)). ⚠️ Currencies ticker should be fiat and has "can_deposit" status must be "true". Use [Asset Status endpoint](/public/http-v4/asset-status-list) to know more about currency.

        provider : str
            [Fiat](/glossary#fiat) currency [provider](/glossary#provider). ⚠️ Currency provider should be taken from [Asset Status endpoint](/public/http-v4/asset-status-list) response.

        amount : str
            Deposit amount

        request : str
            Request signature

        nonce : str
            Unique request identifier

        unique_id : typing.Optional[str]
            Unique transaction identifier on client's side

        customer : typing.Optional[GetFiatDepositUrlRequestCustomer]
            Customer information (required for USD/EUR with VISAMASTER [provider](/glossary#provider))

        success_link : typing.Optional[str]
            Customer will be redirected to this URL by acquiring [provider](/glossary#provider) after success deposit. To activate this feature, please contact support

        failure_link : typing.Optional[str]
            Customer will be redirected to this URL in case of fail or rejection on acquiring provider side. To activate this feature, please contact support

        return_link : typing.Optional[str]
            Customer will be redirected to the URL defined if selects 'back' option after from the payment success or failure page. To activate this feature, define desired link. If not populated, option 'back' won't be displayed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFiatDepositUrlResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.deposit.get_fiat_deposit_url(ticker='UAH', provider='VISAMASTER', amount='100', unique_id='{{generateID}}', request='{{request}}', nonce='{{nonce}}', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_fiat_deposit_url(
            ticker=ticker,
            provider=provider,
            amount=amount,
            request=request,
            nonce=nonce,
            unique_id=unique_id,
            customer=customer,
            success_link=success_link,
            failure_link=failure_link,
            return_link=return_link,
            request_options=request_options,
        )
        return _response.data

    async def issue_card_token(
        self, *, card_number: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        The endpoint issues a [card token](/glossary#card-token) for the specified card number.

        **Request Headers:**
        - `Authorization`: JWT token from the [Issue JWT token](/private/http-main-v4/issue-jwt-token) response field `data.token` (**Required**)
        - `Content-Type`: `application/json` (**Required**)

        Use the `data.token` value returned by [Issue JWT token](/private/http-main-v4/issue-jwt-token) as the `Authorization` header when calling this Fiat Gateway endpoint.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        card_number : str
            Target card number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.deposit.issue_card_token(card_number='4111111111111111', )
        asyncio.run(main())
        """
        _response = await self._raw_client.issue_card_token(card_number=card_number, request_options=request_options)
        return _response.data

    async def refund_deposit(
        self,
        *,
        address: str,
        request: str,
        nonce: str,
        transaction_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RefundDepositResponse:
        """
        Refund a deposit.

        The system processes refunds only for deposits with status `canceled`.

        Obtain `transactionId` from the `deposit.canceled` webhook (`uniqueId`) or from the deposit/withdraw history in the WhiteBIT interface after support confirms refund availability.

        The refund address must support the same network and asset as the original deposit. The refund address must not be a WhiteBIT address. The refund address can differ from the original deposit sender address.

        <Accordion title="Errors">
        ```json
        {
          "code": 0,
          "message": "Transaction not refundable"
        }
        ```

        ```json
        {
          "code": 0,
          "message": "Validation failed",
          "errors": {
            "transactionId": ["The transaction id field is required."],
            "address": ["The address field is required."]
          }
        }
        ```
        </Accordion>

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        <Note>
        Refund processing does not complete instantly. Use the [refund.successful](/platform/webhook#whitebit-refund-successful) and [refund.failed](/platform/webhook#whitebit-refund-failed) webhooks to receive refund status updates.
        </Note>

        Parameters
        ----------
        address : str
            Destination wallet address for the refund. The address must support the same network and asset as the original deposit. Cannot be a WhiteBIT address. Does not have to match the original deposit address.

        request : str
            Base64-encoded request body. See the [authentication guide](/private/http-auth) for signature generation details.

        nonce : str
            A unique identifier for the request. Use a monotonically increasing value such as a Unix timestamp in milliseconds.

        transaction_id : typing.Optional[str]
            Transaction UUID of the deposit. Obtain from the [deposit.canceled](/platform/webhook) webhook (`uniqueId` field) or from the deposit/withdraw history in the WhiteBIT interface.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RefundDepositResponse
            System accepts refund request

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.deposit.refund_deposit(transaction_id='54bffeb7-7a8f-43f8-bcd8-f14ec10fee85', address='0x1234567890abcdef1234567890abcdef12345678', request='{{request}}', nonce='{{nonce}}', )
        asyncio.run(main())
        """
        _response = await self._raw_client.refund_deposit(
            address=address,
            request=request,
            nonce=nonce,
            transaction_id=transaction_id,
            request_options=request_options,
        )
        return _response.data

    async def create_new_address(
        self,
        *,
        ticker: str,
        request: str,
        nonce: str,
        network: typing.Optional[str] = OMIT,
        type: typing.Optional[CreateNewAddressRequestType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateNewAddressResponse:
        """
        The endpoint creates a new address even when the last created address is not used. The endpoint is not available by default, contact support@whitebit.com to get permissions to use the endpoint.

        **Address types:**

        | Currency | Types               | Default |
        |----------|---------------------|---------|
        | BTC      | p2sh-segwit, bech32 | bech32  |
        | LTC      | p2sh-segwit, bech32 | bech32  |

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's ticker.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        network : typing.Optional[str]
            Currency's network (for multinetwork currencies). Example: OMNI or TRC20 or ERC20. For USDT default network is ERC20(ETH).

        type : typing.Optional[CreateNewAddressRequestType]
            Address type, available for specific currencies list (see address types table in endpoint description)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateNewAddressResponse
            All validations succeeded and creating transaction is started

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.deposit.create_new_address(ticker='XLM', request='{{request}}', nonce='{{nonce}}', )
        asyncio.run(main())
        """
        _response = await self._raw_client.create_new_address(
            ticker=ticker, request=request, nonce=nonce, network=network, type=type, request_options=request_options
        )
        return _response.data
