# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_new_address_response_required_flex_fee import CreateNewAddressResponseRequiredFlexFee


class CreateNewAddressResponseRequired(UniversalBaseModel):
    max_amount: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="maxAmount")] = pydantic.Field(
        default=None
    )
    """
    Max amount of deposit accepted by the exchange. Deposits exceeding this amount are rejected.
    """

    min_amount: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="minAmount")] = pydantic.Field(
        default=None
    )
    """
    Min amount of deposit accepted by the exchange. Deposits below this amount are rejected.
    """

    fixed_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fixedFee")] = pydantic.Field(
        default=None
    )
    """
    Fixed deposit fee
    """

    flex_fee: typing_extensions.Annotated[
        typing.Optional[CreateNewAddressResponseRequiredFlexFee], FieldMetadata(alias="flexFee")
    ] = pydantic.Field(default=None)
    """
    Flexible fee - is fee that use percent rate
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
