# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_fiat_deposit_url_request_customer_address import GetFiatDepositUrlRequestCustomerAddress


class GetFiatDepositUrlRequestCustomer(UniversalBaseModel):
    """
    Customer information (required for USD/EUR with VISAMASTER [provider](/glossary#provider))
    """

    first_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="firstName")] = pydantic.Field(
        default=None
    )
    """
    Customer billing first name.
    
    ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
    """

    last_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastName")] = pydantic.Field(
        default=None
    )
    """
    Customer billing last name.
    
    ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer billing email.
    
    ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
    """

    birth_date: typing_extensions.Annotated[typing.Optional[dt.date], FieldMetadata(alias="birthDate")] = (
        pydantic.Field(default=None)
    )
    """
    Customer birth date (Format YYYY-MM-DD).
    
    ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
    """

    address: typing.Optional[GetFiatDepositUrlRequestCustomerAddress] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
