# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetFiatDepositUrlRequestCustomerAddress(UniversalBaseModel):
    line1: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer address line1.
    
    ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
    """

    line2: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer address line2
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer city.
    
    ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
    """

    zip_code: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="zipCode")] = pydantic.Field(
        default=None
    )
    """
    Customer zip-code.
    
    ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
    """

    country_code: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="countryCode")] = (
        pydantic.Field(default=None)
    )
    """
    Customer country code.
    
    ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
