# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_api_v4public_mining_pool_response_data_blocks_item import GetApiV4PublicMiningPoolResponseDataBlocksItem
from .get_api_v4public_mining_pool_response_data_last7days_hash_rate_item import (
    GetApiV4PublicMiningPoolResponseDataLast7DaysHashRateItem,
)


class GetApiV4PublicMiningPoolResponseData(UniversalBaseModel):
    connection_links: typing.Optional[typing.List[str]] = None
    location: typing.Optional[str] = None
    assets: typing.Optional[typing.List[str]] = None
    reward_schemes: typing.Optional[typing.List[str]] = None
    workers: typing.Optional[int] = None
    current_hash_rate: typing.Optional[str] = None
    last7days_hash_rate: typing.Optional[typing.List[GetApiV4PublicMiningPoolResponseDataLast7DaysHashRateItem]] = None
    blocks: typing.Optional[typing.List[GetApiV4PublicMiningPoolResponseDataBlocksItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
