# This file was auto-generated by Fern from our API Definition.

import typing

GetApiV4PublicPlatformStatusResponseStatus = typing.Union[
    typing.Literal["system operational", "system maintenance"], typing.Any
]
