# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_api_v4public_markets_response_item_type import GetApiV4PublicMarketsResponseItemType


class GetApiV4PublicMarketsResponseItem(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Market pair name
    """

    stock: str = pydantic.Field()
    """
    Ticker of stock currency
    """

    money: str = pydantic.Field()
    """
    Ticker of money currency
    """

    stock_prec: typing_extensions.Annotated[str, FieldMetadata(alias="stockPrec")] = pydantic.Field()
    """
    Stock currency precision
    """

    money_prec: typing_extensions.Annotated[str, FieldMetadata(alias="moneyPrec")] = pydantic.Field()
    """
    Precision of money currency
    """

    fee_prec: typing_extensions.Annotated[str, FieldMetadata(alias="feePrec")] = pydantic.Field()
    """
    Fee precision
    """

    maker_fee: typing_extensions.Annotated[str, FieldMetadata(alias="makerFee")] = pydantic.Field()
    """
    Default maker fee ratio
    """

    taker_fee: typing_extensions.Annotated[str, FieldMetadata(alias="takerFee")] = pydantic.Field()
    """
    Default taker fee ratio
    """

    min_amount: typing_extensions.Annotated[str, FieldMetadata(alias="minAmount")] = pydantic.Field()
    """
    Minimal amount of stock to trade
    """

    min_total: typing_extensions.Annotated[str, FieldMetadata(alias="minTotal")] = pydantic.Field()
    """
    Minimal amount of money to trade
    """

    max_total: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="maxTotal")] = pydantic.Field(
        default=None
    )
    """
    Maximum total (amount * price) of money to trade
    """

    trades_enabled: typing_extensions.Annotated[bool, FieldMetadata(alias="tradesEnabled")] = pydantic.Field()
    """
    Indicates whether trading is enabled
    """

    is_collateral: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isCollateral")] = (
        pydantic.Field(default=None)
    )
    """
    Indicates whether margin trading is enabled
    """

    type: GetApiV4PublicMarketsResponseItemType = pydantic.Field()
    """
    Market type. Possible values: spot, futures
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
