# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetApiV4PublicTickerResponseValue(UniversalBaseModel):
    base_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    CoinMarketCap ID of base currency; 0 - if unknown
    """

    quote_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    CoinMarketCap ID of quote currency; 0 - if unknown
    """

    last_price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last price
    """

    quote_volume: typing.Optional[str] = pydantic.Field(default=None)
    """
    Volume in quote currency
    """

    base_volume: typing.Optional[str] = pydantic.Field(default=None)
    """
    Volume in base currency
    """

    is_frozen: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether trading is disabled
    """

    change: typing.Optional[str] = pydantic.Field(default=None)
    """
    Change in percent between open and last prices
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
