# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetApiV4PublicFundingHistoryMarketResponseItem(UniversalBaseModel):
    funding_time: typing_extensions.Annotated[str, FieldMetadata(alias="fundingTime")] = pydantic.Field()
    """
    Timestamp when the funding executed
    """

    funding_rate: typing_extensions.Annotated[str, FieldMetadata(alias="fundingRate")] = pydantic.Field()
    """
    Funding rate value
    """

    market: str = pydantic.Field()
    """
    Market name
    """

    settlement_price: typing_extensions.Annotated[str, FieldMetadata(alias="settlementPrice")] = pydantic.Field()
    """
    Price at which the funding settled
    """

    rate_calculated_time: typing_extensions.Annotated[str, FieldMetadata(alias="rateCalculatedTime")] = pydantic.Field()
    """
    Timestamp of the funding rate calculation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
