# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_api_v4public_trades_market_response_item_type import GetApiV4PublicTradesMarketResponseItemType


class GetApiV4PublicTradesMarketResponseItem(UniversalBaseModel):
    trade_id: typing_extensions.Annotated[int, FieldMetadata(alias="tradeID")] = pydantic.Field()
    """
    A unique ID associated with the trade for the currency pair transaction Note: Unix timestamp does not qualify as trade_id.
    """

    price: str = pydantic.Field()
    """
    Transaction price in quote pair volume.
    """

    quote_volume: str = pydantic.Field()
    """
    Transaction amount in quote pair volume.
    """

    base_volume: str = pydantic.Field()
    """
    Transaction amount in base pair volume.
    """

    trade_timestamp: int = pydantic.Field()
    """
    Unix timestamp in milliseconds, identifies when the transaction occurred.
    """

    type: GetApiV4PublicTradesMarketResponseItemType = pydantic.Field()
    """
    Used to determine whether or not the transaction originated as a buy or sell. Buy – Identifies an ask that was removed from the order book. Sell – Identifies a bid that was removed from the order book.
    """

    rpi: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates that the trade originates from a Retail Price Improvement (RPI) order.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
