# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AssetNetworks(UniversalBaseModel):
    """
    Currency networks
    """

    deposits: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Networks available for depositing
    """

    withdraws: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Networks available for withdrawing
    """

    default: typing.Optional[str] = pydantic.Field(default=None)
    """
    Default network for depositing / withdrawing if available
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
