# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BalanceSpotRequest(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Unique request identifier
    """

    method: typing.Literal["balanceSpot_request"] = pydantic.Field(default="balanceSpot_request")
    """
    Method name. Fixed value: `balanceSpot_request`.
    """

    params: typing.List[str] = pydantic.Field()
    """
    Array of asset tickers to query. Empty array returns all balances.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
