# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .balance_spot_update_params_item_value import BalanceSpotUpdateParamsItemValue


class BalanceSpotUpdate(UniversalBaseModel):
    id: typing.Optional[typing.Optional[typing.Any]] = pydantic.Field(default=None)
    """
    Update events have null id
    """

    method: typing.Literal["balanceSpot_update"] = pydantic.Field(default="balanceSpot_update")
    """
    Method name. Fixed value: `balanceSpot_update`.
    """

    params: typing.List[typing.Dict[str, BalanceSpotUpdateParamsItemValue]] = pydantic.Field()
    """
    Array containing balance updates for subscribed assets
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
