# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BookTickerSubscribe(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Unique request identifier
    """

    method: typing.Literal["bookTicker_subscribe"] = pydantic.Field(default="bookTicker_subscribe")
    """
    Method name. Fixed value: `bookTicker_subscribe`.
    """

    params: typing.List[str]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
