# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BorrowsEventsUpdate(UniversalBaseModel):
    id: typing.Optional[typing.Optional[typing.Any]] = pydantic.Field(default=None)
    """
    Update events have null id
    """

    method: typing.Literal["borrowsAccountMargin_update"] = pydantic.Field(default="borrowsAccountMargin_update")
    """
    Method name. Fixed value: `borrowsAccountMargin_update`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Event tuple:
    - [0] Event type (1=Margin call, 2=Liquidation)
    - [1] Borrow object with all borrow details
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
