# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .convert_history_response_records_item import ConvertHistoryResponseRecordsItem


class ConvertHistoryResponse(UniversalBaseModel):
    records: typing.Optional[typing.List[ConvertHistoryResponseRecordsItem]] = None
    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of records
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Limit used in request
    """

    offset: typing.Optional[int] = pydantic.Field(default=None)
    """
    Offset used in request
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
