# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealsUpdate(UniversalBaseModel):
    id: typing.Optional[typing.Optional[typing.Any]] = pydantic.Field(default=None)
    """
    Update events have null id
    """

    method: typing.Literal["deals_update"] = pydantic.Field(default="deals_update")
    """
    Method name. Fixed value: `deals_update`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Update event tuple (11 elements):
    - [0] Deal ID
    - [1] Deal time (Unix timestamp)
    - [2] Market
    - [3] Order ID
    - [4] Price
    - [5] Stock amount
    - [6] Deal fee
    - [7] Client order ID
    - [8] Side (1=sell, 2=buy)
    - [9] Role (1=maker, 2=taker)
    - [10] Fee asset
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
