# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealsSubscribe(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Unique request identifier
    """

    method: typing.Literal["deals_subscribe"] = pydantic.Field(default="deals_subscribe")
    """
    Method name. Fixed value: `deals_subscribe`.
    """

    params: typing.List[typing.List[str]] = pydantic.Field()
    """
    Array containing array of markets
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
