# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DepthUpdate(UniversalBaseModel):
    id: typing.Optional[typing.Optional[typing.Any]] = None
    method: typing.Literal["depth_update"] = pydantic.Field(default="depth_update")
    """
    Method name. Fixed value: `depth_update`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Update event parameters:
    - [0] Full reload flag (true=full snapshot, false=incremental)
    - [1] Order book data (DepthUpdateData object)
    - [2] Market name
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
