# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .depth_level import DepthLevel


class DepthUpdateData(UniversalBaseModel):
    timestamp: float = pydantic.Field()
    """
    Timestamp from matchengine
    """

    update_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Update ID
    """

    past_update_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Previous update ID (present in incremental updates only, not in first snapshot)
    """

    asks: typing.List[DepthLevel]
    bids: typing.List[DepthLevel]
    event_time: float = pydantic.Field()
    """
    Event time
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
