# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DepthSubscribe(UniversalBaseModel):
    id: int
    method: typing.Literal["depth_subscribe"] = pydantic.Field(default="depth_subscribe")
    """
    Method name. Fixed value: `depth_subscribe`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Subscription parameters:
    - [0] Market name
    - [1] Limit (1, 5, 10, 20, 30, 50, or 100)
    - [2] Price interval units
    - [3] Multiple subscription flag (true=add, false=unsubscribe all)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
