# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FlexPlan(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Flex plan identifier
    """

    ticker: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency [ticker](/glossary#ticker)
    """

    min_investment: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="minInvestment")] = (
        pydantic.Field(default=None)
    )
    """
    Minimum investment amount
    """

    max_investment: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="maxInvestment")] = (
        pydantic.Field(default=None)
    )
    """
    Maximum investment amount
    """

    max_rate: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="maxRate")] = pydantic.Field(
        default=None
    )
    """
    Maximum interest rate
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
