# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FlexInvestmentHistory(UniversalBaseModel):
    created_at: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="createdAt")] = pydantic.Field(
        default=None
    )
    """
    Transaction creation timestamp
    """

    plan_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="planId")] = pydantic.Field(
        default=None
    )
    """
    Flex plan identifier
    """

    investment_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="investmentId")] = (
        pydantic.Field(default=None)
    )
    """
    Flex investment identifier
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transaction currency
    """

    amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transaction amount
    """

    transaction_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transaction identifier
    """

    action_type: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="actionType")] = pydantic.Field(
        default=None
    )
    """
    Action type: 1-INVEST, 2-REINVEST, 3-WITHDRAW_FROM_INVESTMENT, 4-DAILY_EARNING, 5-CLOSE_INVESTMENT, 6-OPEN_INVESTMENT
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
