# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class InterestPayment(UniversalBaseModel):
    plan_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="planId")] = pydantic.Field(
        default=None
    )
    """
    Invest plan identifier
    """

    investment_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="investmentId")] = (
        pydantic.Field(default=None)
    )
    """
    Investment identifier
    """

    amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Interest amount
    """

    ticker: typing.Optional[str] = pydantic.Field(default=None)
    """
    Interest currency [ticker](/glossary#ticker)
    """

    timestamp: typing.Optional[int] = pydantic.Field(default=None)
    """
    Transaction timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
