# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MarketUpdate(UniversalBaseModel):
    id: typing.Optional[typing.Optional[typing.Any]] = None
    method: typing.Literal["market_update"] = pydantic.Field(default="market_update")
    """
    Method name. Fixed value: `market_update`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Update event parameters:
    - [0] Market name
    - [1] MarketStatistics object
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
