# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MarketTodayStatistics(UniversalBaseModel):
    last: str = pydantic.Field()
    """
    Last price
    """

    open: str = pydantic.Field()
    """
    Open price at today's start (UTC midnight)
    """

    high: str = pydantic.Field()
    """
    Highest price today
    """

    low: str = pydantic.Field()
    """
    Lowest price today
    """

    volume: str = pydantic.Field()
    """
    Volume in [stock](/glossary#stock) currency
    """

    deal: str = pydantic.Field()
    """
    Volume in [money](/glossary#money) currency
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
