# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MarketTodaySubscribe(UniversalBaseModel):
    id: int
    method: typing.Literal["marketToday_subscribe"] = pydantic.Field(default="marketToday_subscribe")
    """
    Method name. Fixed value: `marketToday_subscribe`.
    """

    params: typing.List[str]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
