# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MiningReward(UniversalBaseModel):
    mining_account_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="miningAccountName")] = (
        pydantic.Field(default=None)
    )
    """
    Mining account name
    """

    total_reward: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="totalReward")] = (
        pydantic.Field(default=None)
    )
    """
    Total reward amount
    """

    reward: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reward amount (without fee)
    """

    fee: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fee amount
    """

    fpps_rate: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fppsRate")] = pydantic.Field(
        default=None
    )
    """
    FPPS rate
    """

    hash_rate: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="hashRate")] = pydantic.Field(
        default=None
    )
    """
    Hash rate
    """

    date: typing.Optional[int] = pydantic.Field(default=None)
    """
    Reward date timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
