# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .depth_level import DepthLevel


class OrderBook(UniversalBaseModel):
    timestamp: float = pydantic.Field()
    """
    Timestamp from matchengine
    """

    asks: typing.List[DepthLevel] = pydantic.Field()
    """
    Asks sorted ascending
    """

    bids: typing.List[DepthLevel] = pydantic.Field()
    """
    Bids sorted descending
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
