# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OrdersExecutedSubscribe(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Unique request identifier
    """

    method: typing.Literal["ordersExecuted_subscribe"] = pydantic.Field(default="ordersExecuted_subscribe")
    """
    Method name. Fixed value: `ordersExecuted_subscribe`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Subscription parameters tuple:
    - [0] Array of market names
    - [1] Filter (0=Limit and Market, 1=Limit, 2=Market)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
