# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OrdersExecutedRequest(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Unique request identifier
    """

    method: typing.Literal["ordersExecuted_request"] = pydantic.Field(default="ordersExecuted_request")
    """
    Method name. Fixed value: `ordersExecuted_request`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Query parameters tuple:
    - [0] Filter object with market and order_types
    - [1] Offset
    - [2] Limit (max 100)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
