# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OrdersPendingRequest(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Unique request identifier
    """

    method: typing.Literal["ordersPending_request"] = pydantic.Field(default="ordersPending_request")
    """
    Method name. Fixed value: `ordersPending_request`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Array with market, offset, and limit
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
