# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OrderbookResponse(UniversalBaseModel):
    ticker_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Market Name
    """

    timestamp: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current timestamp
    """

    asks: typing.Optional[typing.List[typing.List[str]]] = pydantic.Field(default=None)
    """
    Array of ask orders
    """

    bids: typing.Optional[typing.List[typing.List[str]]] = pydantic.Field(default=None)
    """
    Array of bid orders
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
