# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .positions_update_params import PositionsUpdateParams


class PositionsUpdate(UniversalBaseModel):
    id: typing.Optional[typing.Optional[typing.Any]] = pydantic.Field(default=None)
    """
    Update events have null id
    """

    method: typing.Literal["positionsMargin_update"] = pydantic.Field(default="positionsMargin_update")
    """
    Method name. Fixed value: `positionsMargin_update`.
    """

    params: PositionsUpdateParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
