# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class SubAccountTransfer(UniversalBaseModel):
    transaction_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transaction identifier. Same value as id. Correlate with the transfer endpoint response using the transactionId field.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transfer identifier
    """

    direction: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transfer direction (main_to_sub or sub_to_main)
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency transferred
    """

    amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transfer amount
    """

    created_at: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="createdAt")] = pydantic.Field(
        default=None
    )
    """
    Transfer creation timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
