# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .sub_account_api_key_list_access_endpoints_item import SubAccountApiKeyListAccessEndpointsItem


class SubAccountApiKeyList(UniversalBaseModel):
    sub_account_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="subAccountId")] = None
    id: typing.Optional[str] = None
    title: typing.Optional[str] = None
    is_enabled: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isEnabled")] = None
    api_key: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="apiKey")] = None
    api_secret: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="apiSecret")] = pydantic.Field(
        default=None
    )
    """
    Empty for security (only shown during creation)
    """

    type: typing.Optional[str] = None
    last_activity: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="lastActivity")] = None
    restrict_access: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="restrictAccess")] = None
    access_endpoints: typing_extensions.Annotated[
        typing.Optional[typing.List[SubAccountApiKeyListAccessEndpointsItem]], FieldMetadata(alias="accessEndpoints")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
