# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .sub_account_api_key_access_endpoints_item import SubAccountApiKeyAccessEndpointsItem


class SubAccountApiKey(UniversalBaseModel):
    sub_account_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="subAccountId")] = (
        pydantic.Field(default=None)
    )
    """
    Sub-account identifier
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    API key identifier
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    API key title/name
    """

    is_enabled: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isEnabled")] = pydantic.Field(
        default=None
    )
    """
    Whether the API key is enabled
    """

    api_key: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="apiKey")] = pydantic.Field(
        default=None
    )
    """
    API key
    """

    api_secret: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="apiSecret")] = pydantic.Field(
        default=None
    )
    """
    API secret
    """

    type: typing.Optional[int] = pydantic.Field(default=None)
    """
    API key type (1 - info and trading, 2 - info, trading, deposit and withdraw)
    """

    last_activity: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="lastActivity")] = (
        pydantic.Field(default=None)
    )
    """
    Last activity timestamp
    """

    restrict_access: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="restrictAccess")] = (
        pydantic.Field(default=None)
    )
    """
    Whether access is restricted
    """

    access_endpoints: typing_extensions.Annotated[
        typing.Optional[typing.List[SubAccountApiKeyAccessEndpointsItem]], FieldMetadata(alias="accessEndpoints")
    ] = pydantic.Field(default=None)
    """
    List of allowed endpoints
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
