# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .trade_type import TradeType


class Trade(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Trade ID
    """

    time: float = pydantic.Field()
    """
    Trade time (Unix timestamp with milliseconds)
    """

    price: str = pydantic.Field()
    """
    Trade price
    """

    amount: str = pydantic.Field()
    """
    Trade amount
    """

    type: TradeType = pydantic.Field()
    """
    Trade type (buy/sell)
    """

    rpi: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the trade involved a Retail Price Improvement (RPI) order
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
