# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TradesSubscribe(UniversalBaseModel):
    id: int
    method: typing.Literal["trades_subscribe"] = pydantic.Field(default="trades_subscribe")
    """
    Method name. Fixed value: `trades_subscribe`.
    """

    params: typing.List[str] = pydantic.Field()
    """
    Market names (empty array to subscribe to all markets)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
