# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UnsubscribeRequest(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Unique request identifier
    """

    method: typing.Literal["positionsMargin_unsubscribe"] = pydantic.Field(default="positionsMargin_unsubscribe")
    """
    Method name. Fixed value: `positionsMargin_unsubscribe`.
    """

    params: typing.List[typing.Optional[typing.Any]] = pydantic.Field()
    """
    Empty array for unsubscribe
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
