# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from ..environment import WhitebitApiEnvironment
from .http_client import AsyncHttpClient, HttpClient


class BaseClientWrapper:
    def __init__(
        self,
        *,
        txc_apikey: str,
        token: typing.Union[str, typing.Callable[[], str]],
        environment: WhitebitApiEnvironment,
        timeout: typing.Optional[float] = None,
    ):
        self._txc_apikey = txc_apikey
        self._token = token
        self._environment = environment
        self._timeout = timeout

    def get_headers(self) -> typing.Dict[str, str]:
        headers: typing.Dict[str, str] = {
            "X-Fern-Language": "Python",
        }
        headers["X-TXC-APIKEY"] = self._txc_apikey
        headers["Authorization"] = f"Bearer {self._get_token()}"
        return headers

    def _get_token(self) -> str:
        if isinstance(self._token, str):
            return self._token
        else:
            return self._token()

    def get_environment(self) -> WhitebitApiEnvironment:
        return self._environment

    def get_timeout(self) -> typing.Optional[float]:
        return self._timeout


class SyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        txc_apikey: str,
        token: typing.Union[str, typing.Callable[[], str]],
        environment: WhitebitApiEnvironment,
        timeout: typing.Optional[float] = None,
        httpx_client: httpx.Client,
    ):
        super().__init__(txc_apikey=txc_apikey, token=token, environment=environment, timeout=timeout)
        self.httpx_client = HttpClient(
            httpx_client=httpx_client, base_headers=self.get_headers, base_timeout=self.get_timeout
        )


class AsyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        txc_apikey: str,
        token: typing.Union[str, typing.Callable[[], str]],
        environment: WhitebitApiEnvironment,
        timeout: typing.Optional[float] = None,
        httpx_client: httpx.AsyncClient,
    ):
        super().__init__(txc_apikey=txc_apikey, token=token, environment=environment, timeout=timeout)
        self.httpx_client = AsyncHttpClient(
            httpx_client=httpx_client, base_headers=self.get_headers, base_timeout=self.get_timeout
        )
