# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from .types.apply_code_response import ApplyCodeResponse
from .types.create_code_response import CreateCodeResponse
from .types.get_codes_history_response import GetCodesHistoryResponse
from .types.get_my_codes_response import GetMyCodesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawCodesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_code(
        self,
        *,
        ticker: str,
        amount: str,
        request: str,
        nonce: str,
        passphrase: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateCodeResponse]:
        """
        The endpoint creates [WhiteBIT code](/glossary#whitebit-codes).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's [ticker](/glossary#ticker). Example: BTC

        amount : str
            Amount to transfer. Max [precision](/glossary#precision) = 8, value must be greater than zero and less than or equal to the [main balance](/glossary#balance-main).

        request : str
            Request signature

        nonce : str
            Unique request identifier

        passphrase : typing.Optional[str]
            Passphrase for applying [WhiteBIT codes](/glossary#whitebit-codes). Passphrase must contain only latin letters, numbers and symbols (like !@#$%^, no whitespaces). Max: 25 symbols.

        description : typing.Optional[str]
            Additional text description for [code](/glossary#whitebit-codes). Visible only for creator. Max: 75 symbols.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateCodeResponse]
            All validations succeeded and creating transaction is started
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/main-account/codes",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "ticker": ticker,
                "amount": amount,
                "passphrase": passphrase,
                "description": description,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateCodeResponse,
                    parse_obj_as(
                        type_=CreateCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def apply_code(
        self,
        *,
        code: str,
        request: str,
        nonce: str,
        passphrase: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApplyCodeResponse]:
        """
        The endpoint applies [WhiteBIT code](/glossary#whitebit-codes).

        <Warning>
        Rate limit: 60 requests/1 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        code : str
            [Code](/glossary#whitebit-codes) that will be applied.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        passphrase : typing.Optional[str]
            Should be provided if the [code](/glossary#whitebit-codes) was created with passphrase. Max: 25 symbols.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApplyCodeResponse]
            All validations succeeded and creating transaction is started
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/main-account/codes/apply",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "code": code,
                "passphrase": passphrase,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApplyCodeResponse,
                    parse_obj_as(
                        type_=ApplyCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_my_codes(
        self,
        *,
        request: str,
        nonce: str,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetMyCodesResponse]:
        """
        The endpoint retrieves the list of [WhiteBIT codes](/glossary#whitebit-codes) created by my account.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        limit : typing.Optional[int]
            LIMIT is a special clause used to limit records a particular query can return.

        offset : typing.Optional[int]
            Use the OFFSET clause to return entries starting from a particular line.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetMyCodesResponse]
            All validations succeeded and creating transaction is started
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/main-account/codes/my",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "limit": limit,
                "offset": offset,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetMyCodesResponse,
                    parse_obj_as(
                        type_=GetMyCodesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_codes_history(
        self,
        *,
        request: str,
        nonce: str,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetCodesHistoryResponse]:
        """
        The endpoint retrieves the whole [codes](/glossary#whitebit-codes) history for the account.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        limit : typing.Optional[int]
            LIMIT is a special clause used to limit records a particular query can return.

        offset : typing.Optional[int]
            Use the OFFSET clause to return entries starting from a particular line.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetCodesHistoryResponse]
            All validations succeeded and creating transaction is started
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/main-account/codes/history",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "limit": limit,
                "offset": offset,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetCodesHistoryResponse,
                    parse_obj_as(
                        type_=GetCodesHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawCodesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_code(
        self,
        *,
        ticker: str,
        amount: str,
        request: str,
        nonce: str,
        passphrase: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateCodeResponse]:
        """
        The endpoint creates [WhiteBIT code](/glossary#whitebit-codes).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's [ticker](/glossary#ticker). Example: BTC

        amount : str
            Amount to transfer. Max [precision](/glossary#precision) = 8, value must be greater than zero and less than or equal to the [main balance](/glossary#balance-main).

        request : str
            Request signature

        nonce : str
            Unique request identifier

        passphrase : typing.Optional[str]
            Passphrase for applying [WhiteBIT codes](/glossary#whitebit-codes). Passphrase must contain only latin letters, numbers and symbols (like !@#$%^, no whitespaces). Max: 25 symbols.

        description : typing.Optional[str]
            Additional text description for [code](/glossary#whitebit-codes). Visible only for creator. Max: 75 symbols.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateCodeResponse]
            All validations succeeded and creating transaction is started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/main-account/codes",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "ticker": ticker,
                "amount": amount,
                "passphrase": passphrase,
                "description": description,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateCodeResponse,
                    parse_obj_as(
                        type_=CreateCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def apply_code(
        self,
        *,
        code: str,
        request: str,
        nonce: str,
        passphrase: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApplyCodeResponse]:
        """
        The endpoint applies [WhiteBIT code](/glossary#whitebit-codes).

        <Warning>
        Rate limit: 60 requests/1 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        code : str
            [Code](/glossary#whitebit-codes) that will be applied.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        passphrase : typing.Optional[str]
            Should be provided if the [code](/glossary#whitebit-codes) was created with passphrase. Max: 25 symbols.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApplyCodeResponse]
            All validations succeeded and creating transaction is started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/main-account/codes/apply",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "code": code,
                "passphrase": passphrase,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApplyCodeResponse,
                    parse_obj_as(
                        type_=ApplyCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_my_codes(
        self,
        *,
        request: str,
        nonce: str,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetMyCodesResponse]:
        """
        The endpoint retrieves the list of [WhiteBIT codes](/glossary#whitebit-codes) created by my account.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        limit : typing.Optional[int]
            LIMIT is a special clause used to limit records a particular query can return.

        offset : typing.Optional[int]
            Use the OFFSET clause to return entries starting from a particular line.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetMyCodesResponse]
            All validations succeeded and creating transaction is started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/main-account/codes/my",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "limit": limit,
                "offset": offset,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetMyCodesResponse,
                    parse_obj_as(
                        type_=GetMyCodesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_codes_history(
        self,
        *,
        request: str,
        nonce: str,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetCodesHistoryResponse]:
        """
        The endpoint retrieves the whole [codes](/glossary#whitebit-codes) history for the account.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        limit : typing.Optional[int]
            LIMIT is a special clause used to limit records a particular query can return.

        offset : typing.Optional[int]
            Use the OFFSET clause to return entries starting from a particular line.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetCodesHistoryResponse]
            All validations succeeded and creating transaction is started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/main-account/codes/history",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "limit": limit,
                "offset": offset,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetCodesHistoryResponse,
                    parse_obj_as(
                        type_=GetCodesHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
