# This file was auto-generated by Fern from our API Definition.

import typing

TransferBetweenBalancesRequestMethod = typing.Union[
    typing.Literal["deposit", "withdraw", "collateral-deposit", "collateral-withdraw"], typing.Any
]
