# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_mining_payout_destination_response_payout_destination import (
    GetMiningPayoutDestinationResponsePayoutDestination,
)


class GetMiningPayoutDestinationResponse(UniversalBaseModel):
    payout_destination: typing_extensions.Annotated[
        typing.Optional[GetMiningPayoutDestinationResponsePayoutDestination], FieldMetadata(alias="payoutDestination")
    ] = pydantic.Field(default=None)
    """
    Payout destination type
    """

    external_address: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="externalAddress")] = (
        pydantic.Field(default=None)
    )
    """
    External BTC address (null if destination is main_balance)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
