# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.sub_account import SubAccount
from .raw_client import AsyncRawSubAccountClient, RawSubAccountClient
from .types.create_sub_account_request_permissions import CreateSubAccountRequestPermissions
from .types.edit_sub_account_request_permissions import EditSubAccountRequestPermissions
from .types.get_sub_account_balances_response_value_item import GetSubAccountBalancesResponseValueItem
from .types.get_sub_account_transfer_history_request_direction import GetSubAccountTransferHistoryRequestDirection
from .types.get_sub_account_transfer_history_response import GetSubAccountTransferHistoryResponse
from .types.list_sub_accounts_response import ListSubAccountsResponse
from .types.sub_account_transfer_request_direction import SubAccountTransferRequestDirection
from .types.sub_account_transfer_response import SubAccountTransferResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SubAccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSubAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubAccountClient
        """
        return self._raw_client

    def create_sub_account(
        self,
        *,
        alias: str,
        permissions: CreateSubAccountRequestPermissions,
        email: typing.Optional[str] = OMIT,
        share_kyc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubAccount:
        """
        The endpoint creates new [sub-account](/glossary#sub-account).

        <Note>
        The `email` field requirement depends on the `shareKyc` parameter:
        - When `shareKyc` is `false` or not provided: `email` is **required**
        - When `shareKyc` is `true`: `email` is **optional**
        </Note>

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        alias : str
            Name for sub-account

        permissions : CreateSubAccountRequestPermissions

        email : typing.Optional[str]
            Sub-account email (required when shareKyc is false)

        share_kyc : typing.Optional[bool]
            If KYC shared with main account

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubAccount
            Sub-account created successfully

        Examples
        --------
        from whitebit import WhitebitApi
        from whitebit.sub_account import CreateSubAccountRequestPermissions
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.create_sub_account(alias='trading_bot', permissions=CreateSubAccountRequestPermissions(spot_enabled=True, collateral_enabled=False, ), )
        """
        _response = self._raw_client.create_sub_account(
            alias=alias, permissions=permissions, email=email, share_kyc=share_kyc, request_options=request_options
        )
        return _response.data

    def delete_sub_account(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint deletes [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Sub-account deleted successfully

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.delete_sub_account(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', )
        """
        _response = self._raw_client.delete_sub_account(id=id, request_options=request_options)
        return _response.data

    def edit_sub_account(
        self,
        *,
        id: str,
        alias: str,
        permissions: EditSubAccountRequestPermissions,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint edits [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        alias : str
            Name for sub-account

        permissions : EditSubAccountRequestPermissions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Sub-account edited successfully

        Examples
        --------
        from whitebit import WhitebitApi
        from whitebit.sub_account import EditSubAccountRequestPermissions
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.edit_sub_account(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', alias='training', permissions=EditSubAccountRequestPermissions(spot_enabled=True, collateral_enabled=False, ), )
        """
        _response = self._raw_client.edit_sub_account(
            id=id, alias=alias, permissions=permissions, request_options=request_options
        )
        return _response.data

    def list_sub_accounts(
        self,
        *,
        search: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSubAccountsResponse:
        """
        The endpoint returns list of current user [sub-accounts](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        search : typing.Optional[str]
            Search term

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSubAccountsResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.list_sub_accounts()
        """
        _response = self._raw_client.list_sub_accounts(
            search=search, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def transfer(
        self,
        *,
        id: str,
        direction: SubAccountTransferRequestDirection,
        amount: str,
        ticker: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubAccountTransferResponse:
        """
        The endpoint creates transfer from main account to [sub-account](/glossary#sub-account) or vice versa.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        direction : SubAccountTransferRequestDirection
            Transfer direction

        amount : str
            Transfer amount (min 0.00000001)

        ticker : str
            Currency's [ticker](/glossary#ticker)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubAccountTransferResponse
            Transfer successful

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.transfer(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', direction="main_to_sub", amount='0.5', ticker='ETH', )
        """
        _response = self._raw_client.transfer(
            id=id, direction=direction, amount=amount, ticker=ticker, request_options=request_options
        )
        return _response.data

    def block_sub_account(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint blocks [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Sub-account blocked successfully

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.block_sub_account(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', )
        """
        _response = self._raw_client.block_sub_account(id=id, request_options=request_options)
        return _response.data

    def unblock_sub_account(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint unblocks [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Sub-account unblocked successfully

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.unblock_sub_account(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', )
        """
        _response = self._raw_client.unblock_sub_account(id=id, request_options=request_options)
        return _response.data

    def get_sub_account_balances(
        self, *, id: str, ticker: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.List[GetSubAccountBalancesResponseValueItem]]:
        """
        The endpoint returns [sub-account](/glossary#sub-account) balances.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        ticker : typing.Optional[str]
            Currency's ticker (if not provided, returns data by all currencies)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.List[GetSubAccountBalancesResponseValueItem]]
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.get_sub_account_balances(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', ticker='USDC', )
        """
        _response = self._raw_client.get_sub_account_balances(id=id, ticker=ticker, request_options=request_options)
        return _response.data

    def get_sub_account_transfer_history(
        self,
        *,
        id: str,
        direction: typing.Optional[GetSubAccountTransferHistoryRequestDirection] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSubAccountTransferHistoryResponse:
        """
        The endpoint returns history of transfers between main account and [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        direction : typing.Optional[GetSubAccountTransferHistoryRequestDirection]
            Transfer direction (optional)

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSubAccountTransferHistoryResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.sub_account.get_sub_account_transfer_history(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', )
        """
        _response = self._raw_client.get_sub_account_transfer_history(
            id=id, direction=direction, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data


class AsyncSubAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSubAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubAccountClient
        """
        return self._raw_client

    async def create_sub_account(
        self,
        *,
        alias: str,
        permissions: CreateSubAccountRequestPermissions,
        email: typing.Optional[str] = OMIT,
        share_kyc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubAccount:
        """
        The endpoint creates new [sub-account](/glossary#sub-account).

        <Note>
        The `email` field requirement depends on the `shareKyc` parameter:
        - When `shareKyc` is `false` or not provided: `email` is **required**
        - When `shareKyc` is `true`: `email` is **optional**
        </Note>

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        alias : str
            Name for sub-account

        permissions : CreateSubAccountRequestPermissions

        email : typing.Optional[str]
            Sub-account email (required when shareKyc is false)

        share_kyc : typing.Optional[bool]
            If KYC shared with main account

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubAccount
            Sub-account created successfully

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        from whitebit.sub_account import CreateSubAccountRequestPermissions
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.create_sub_account(alias='trading_bot', permissions=CreateSubAccountRequestPermissions(spot_enabled=True, collateral_enabled=False, ), )
        asyncio.run(main())
        """
        _response = await self._raw_client.create_sub_account(
            alias=alias, permissions=permissions, email=email, share_kyc=share_kyc, request_options=request_options
        )
        return _response.data

    async def delete_sub_account(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint deletes [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Sub-account deleted successfully

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.delete_sub_account(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', )
        asyncio.run(main())
        """
        _response = await self._raw_client.delete_sub_account(id=id, request_options=request_options)
        return _response.data

    async def edit_sub_account(
        self,
        *,
        id: str,
        alias: str,
        permissions: EditSubAccountRequestPermissions,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint edits [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        alias : str
            Name for sub-account

        permissions : EditSubAccountRequestPermissions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Sub-account edited successfully

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        from whitebit.sub_account import EditSubAccountRequestPermissions
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.edit_sub_account(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', alias='training', permissions=EditSubAccountRequestPermissions(spot_enabled=True, collateral_enabled=False, ), )
        asyncio.run(main())
        """
        _response = await self._raw_client.edit_sub_account(
            id=id, alias=alias, permissions=permissions, request_options=request_options
        )
        return _response.data

    async def list_sub_accounts(
        self,
        *,
        search: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSubAccountsResponse:
        """
        The endpoint returns list of current user [sub-accounts](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        search : typing.Optional[str]
            Search term

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSubAccountsResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.list_sub_accounts()
        asyncio.run(main())
        """
        _response = await self._raw_client.list_sub_accounts(
            search=search, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def transfer(
        self,
        *,
        id: str,
        direction: SubAccountTransferRequestDirection,
        amount: str,
        ticker: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubAccountTransferResponse:
        """
        The endpoint creates transfer from main account to [sub-account](/glossary#sub-account) or vice versa.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        direction : SubAccountTransferRequestDirection
            Transfer direction

        amount : str
            Transfer amount (min 0.00000001)

        ticker : str
            Currency's [ticker](/glossary#ticker)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubAccountTransferResponse
            Transfer successful

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.transfer(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', direction="main_to_sub", amount='0.5', ticker='ETH', )
        asyncio.run(main())
        """
        _response = await self._raw_client.transfer(
            id=id, direction=direction, amount=amount, ticker=ticker, request_options=request_options
        )
        return _response.data

    async def block_sub_account(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint blocks [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Sub-account blocked successfully

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.block_sub_account(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', )
        asyncio.run(main())
        """
        _response = await self._raw_client.block_sub_account(id=id, request_options=request_options)
        return _response.data

    async def unblock_sub_account(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint unblocks [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Sub-account unblocked successfully

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.unblock_sub_account(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', )
        asyncio.run(main())
        """
        _response = await self._raw_client.unblock_sub_account(id=id, request_options=request_options)
        return _response.data

    async def get_sub_account_balances(
        self, *, id: str, ticker: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.List[GetSubAccountBalancesResponseValueItem]]:
        """
        The endpoint returns [sub-account](/glossary#sub-account) balances.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        ticker : typing.Optional[str]
            Currency's ticker (if not provided, returns data by all currencies)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.List[GetSubAccountBalancesResponseValueItem]]
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.get_sub_account_balances(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', ticker='USDC', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_sub_account_balances(
            id=id, ticker=ticker, request_options=request_options
        )
        return _response.data

    async def get_sub_account_transfer_history(
        self,
        *,
        id: str,
        direction: typing.Optional[GetSubAccountTransferHistoryRequestDirection] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSubAccountTransferHistoryResponse:
        """
        The endpoint returns history of transfers between main account and [sub-account](/glossary#sub-account).

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        id : str
            Sub-account id

        direction : typing.Optional[GetSubAccountTransferHistoryRequestDirection]
            Transfer direction (optional)

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSubAccountTransferHistoryResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.sub_account.get_sub_account_transfer_history(id='8e667b4a-0b71-4988-8af5-9474dbfaeb51', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_sub_account_transfer_history(
            id=id, direction=direction, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data
