# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAuthenticationClient, RawAuthenticationClient
from .types.post_oauth2refresh_token_response import PostOauth2RefreshTokenResponse
from .types.post_oauth2token_response import PostOauth2TokenResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AuthenticationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAuthenticationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAuthenticationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAuthenticationClient
        """
        return self._raw_client

    def o_auth20authorization(
        self,
        *,
        client_id: str,
        state: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        The endpoint initiates the OAuth 2.0 authorization flow for user authentication and obtaining an authorization code.

        **Using the State Parameter (Best Practice)**

        The `state` parameter is crucial for security in OAuth flows:

        - Generate a cryptographically secure random string
        - Store it in the session before redirecting
        - Validate it matches when handling the callback
        - This prevents CSRF attacks
        <Note>
        **Note:** OAuth scopes are predefined during client application setup and cannot be modified during the authorization request. The access token will include all scopes that were approved during client creation.
        </Note>

        Parameters
        ----------
        client_id : str
            The application's client ID

        state : typing.Optional[str]
            A secure random string used to maintain state between the request and callback and prevent CSRF attacks (Recommended)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.authentication.o_auth20authorization(client_id='YOUR_CLIENT_ID', state='SECURE_RANDOM_STATE', )
        """
        _response = self._raw_client.o_auth20authorization(
            client_id=client_id, state=state, request_options=request_options
        )
        return _response.data

    def get_access_token(
        self, *, client_id: str, client_secret: str, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostOauth2TokenResponse:
        """
        The endpoint activates an access token by exchanging an authorization code.

        <Warning>
        **Important Notes:**

        - Access token duration is 300 seconds
        - The IP of the client must be added to WB Allowlist
        </Warning>

        **Request Headers:**
        - Content-Type: application/x-www-form-urlencoded

        Parameters
        ----------
        client_id : str
            The application's client ID

        client_secret : str
            The application's client secret

        code : str
            The authorization code received from the authorization endpoint

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostOauth2TokenResponse
            Successful token exchange

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.authentication.get_access_token(client_id='YOUR_CLIENT_ID', client_secret='YOUR_CLIENT_SECRET', code='AUTHORIZATION_CODE', )
        """
        _response = self._raw_client.get_access_token(
            client_id=client_id, client_secret=client_secret, code=code, request_options=request_options
        )
        return _response.data

    def refresh_token(
        self, *, client_id: str, client_secret: str, token: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostOauth2RefreshTokenResponse:
        """
        This endpoint creates a new access token using a refresh token.

        **Request Headers:**
        - Content-Type: application/x-www-form-urlencoded

        <Warning>
        **Important Notes:**

        - Refresh token duration is 600 seconds
        - Rate limit: 1 request per second
        - The IP of the client must be added to WB Allowlist
        </Warning>

        Parameters
        ----------
        client_id : str
            The application's client ID

        client_secret : str
            The application's client secret

        token : str
            The refresh token received from the token endpoint

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostOauth2RefreshTokenResponse
            Successful token refresh

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.authentication.refresh_token(client_id='YOUR_CLIENT_ID', client_secret='YOUR_CLIENT_SECRET', token='REFRESH_TOKEN', )
        """
        _response = self._raw_client.refresh_token(
            client_id=client_id, client_secret=client_secret, token=token, request_options=request_options
        )
        return _response.data


class AsyncAuthenticationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAuthenticationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAuthenticationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAuthenticationClient
        """
        return self._raw_client

    async def o_auth20authorization(
        self,
        *,
        client_id: str,
        state: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        The endpoint initiates the OAuth 2.0 authorization flow for user authentication and obtaining an authorization code.

        **Using the State Parameter (Best Practice)**

        The `state` parameter is crucial for security in OAuth flows:

        - Generate a cryptographically secure random string
        - Store it in the session before redirecting
        - Validate it matches when handling the callback
        - This prevents CSRF attacks
        <Note>
        **Note:** OAuth scopes are predefined during client application setup and cannot be modified during the authorization request. The access token will include all scopes that were approved during client creation.
        </Note>

        Parameters
        ----------
        client_id : str
            The application's client ID

        state : typing.Optional[str]
            A secure random string used to maintain state between the request and callback and prevent CSRF attacks (Recommended)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.authentication.o_auth20authorization(client_id='YOUR_CLIENT_ID', state='SECURE_RANDOM_STATE', )
        asyncio.run(main())
        """
        _response = await self._raw_client.o_auth20authorization(
            client_id=client_id, state=state, request_options=request_options
        )
        return _response.data

    async def get_access_token(
        self, *, client_id: str, client_secret: str, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostOauth2TokenResponse:
        """
        The endpoint activates an access token by exchanging an authorization code.

        <Warning>
        **Important Notes:**

        - Access token duration is 300 seconds
        - The IP of the client must be added to WB Allowlist
        </Warning>

        **Request Headers:**
        - Content-Type: application/x-www-form-urlencoded

        Parameters
        ----------
        client_id : str
            The application's client ID

        client_secret : str
            The application's client secret

        code : str
            The authorization code received from the authorization endpoint

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostOauth2TokenResponse
            Successful token exchange

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.authentication.get_access_token(client_id='YOUR_CLIENT_ID', client_secret='YOUR_CLIENT_SECRET', code='AUTHORIZATION_CODE', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_access_token(
            client_id=client_id, client_secret=client_secret, code=code, request_options=request_options
        )
        return _response.data

    async def refresh_token(
        self, *, client_id: str, client_secret: str, token: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostOauth2RefreshTokenResponse:
        """
        This endpoint creates a new access token using a refresh token.

        **Request Headers:**
        - Content-Type: application/x-www-form-urlencoded

        <Warning>
        **Important Notes:**

        - Refresh token duration is 600 seconds
        - Rate limit: 1 request per second
        - The IP of the client must be added to WB Allowlist
        </Warning>

        Parameters
        ----------
        client_id : str
            The application's client ID

        client_secret : str
            The application's client secret

        token : str
            The refresh token received from the token endpoint

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostOauth2RefreshTokenResponse
            Successful token refresh

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.authentication.refresh_token(client_id='YOUR_CLIENT_ID', client_secret='YOUR_CLIENT_SECRET', token='REFRESH_TOKEN', )
        asyncio.run(main())
        """
        _response = await self._raw_client.refresh_token(
            client_id=client_id, client_secret=client_secret, token=token, request_options=request_options
        )
        return _response.data
