# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .cancel_oco_order_response_stop_loss_activation_condition import CancelOcoOrderResponseStopLossActivationCondition
from .cancel_oco_order_response_stop_loss_side import CancelOcoOrderResponseStopLossSide


class CancelOcoOrderResponseStopLoss(UniversalBaseModel):
    """
    Cancelled stop loss order details
    """

    order_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Order identifier
    """

    client_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Custom order identifier. Empty string if not specified
    """

    market: typing.Optional[str] = pydantic.Field(default=None)
    """
    Market name
    """

    side: typing.Optional[CancelOcoOrderResponseStopLossSide] = pydantic.Field(default=None)
    """
    Order side
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order type
    """

    timestamp: typing.Optional[float] = pydantic.Field(default=None)
    """
    Timestamp of order creation
    """

    deal_money: typing.Optional[str] = pydantic.Field(default=None)
    """
    Executed amount in money
    """

    deal_stock: typing.Optional[str] = pydantic.Field(default=None)
    """
    Executed amount in stock
    """

    amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order amount
    """

    taker_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="takerFee")] = pydantic.Field(
        default=None
    )
    """
    Taker fee ratio
    """

    maker_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="makerFee")] = pydantic.Field(
        default=None
    )
    """
    Maker fee ratio
    """

    left: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unexecuted amount in stock
    """

    deal_fee: typing.Optional[str] = pydantic.Field(default=None)
    """
    Executed fee by deal
    """

    post_only: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Post-only flag
    """

    mtime: typing.Optional[float] = pydantic.Field(default=None)
    """
    Timestamp of order modification
    """

    price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order price
    """

    activation_price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Activation price
    """

    activation_condition: typing.Optional[CancelOcoOrderResponseStopLossActivationCondition] = pydantic.Field(
        default=None
    )
    """
    Activation condition
    """

    activated: typing.Optional[int] = pydantic.Field(default=None)
    """
    Activation status (0 - not activated, 1 - activated)
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order status
    """

    stp: typing.Optional[str] = pydantic.Field(default=None)
    """
    Self trade prevention mode
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
