# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class CollateralAccountSummaryResponse(UniversalBaseModel):
    equity: typing.Optional[str] = pydantic.Field(default=None)
    """
    Total equity value of the collateral account
    """

    margin: typing.Optional[str] = pydantic.Field(default=None)
    """
    Total margin used
    """

    free_margin: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="freeMargin")] = pydantic.Field(
        default=None
    )
    """
    Available margin for trading
    """

    unrealized_funding: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="unrealizedFunding")] = (
        pydantic.Field(default=None)
    )
    """
    Unrealized funding payments
    """

    pnl: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unrealized profit and loss
    """

    leverage: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current leverage level
    """

    margin_fraction: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="marginFraction")] = (
        pydantic.Field(default=None)
    )
    """
    Margin fraction ratio (margin / equity)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
