# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_collateral_stop_limit_order_response_oto import CreateCollateralStopLimitOrderResponseOto
from .create_collateral_stop_limit_order_response_position_side import (
    CreateCollateralStopLimitOrderResponsePositionSide,
)
from .create_collateral_stop_limit_order_response_side import CreateCollateralStopLimitOrderResponseSide
from .create_collateral_stop_limit_order_response_status import CreateCollateralStopLimitOrderResponseStatus


class CreateCollateralStopLimitOrderResponse(UniversalBaseModel):
    order_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unique order identifier
    """

    client_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Custom client order identifier. Empty string if not specified
    """

    market: typing.Optional[str] = pydantic.Field(default=None)
    """
    Market name
    """

    side: typing.Optional[CreateCollateralStopLimitOrderResponseSide] = pydantic.Field(default=None)
    """
    Order side
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order type
    """

    timestamp: typing.Optional[float] = pydantic.Field(default=None)
    """
    Timestamp of order creation in Unix format
    """

    deal_money: typing.Optional[str] = pydantic.Field(default=None)
    """
    Amount in money currency that is finished
    """

    deal_stock: typing.Optional[str] = pydantic.Field(default=None)
    """
    Amount in stock currency that is finished
    """

    amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order amount
    """

    left: typing.Optional[str] = pydantic.Field(default=None)
    """
    Remaining amount that must be finished
    """

    deal_fee: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fee in money that is paid when order is finished
    """

    price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order price
    """

    activation_price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Price at which the stop-limit order activates
    """

    status: typing.Optional[CreateCollateralStopLimitOrderResponseStatus] = pydantic.Field(default=None)
    """
    Order status
    """

    stp: typing.Optional[str] = pydantic.Field(default=None)
    """
    Self trade prevention mode
    """

    oto: typing.Optional[CreateCollateralStopLimitOrderResponseOto] = pydantic.Field(default=None)
    """
    OTO order data when stopLoss or takeProfit is specified
    """

    position_side: typing_extensions.Annotated[
        typing.Optional[CreateCollateralStopLimitOrderResponsePositionSide], FieldMetadata(alias="positionSide")
    ] = pydantic.Field(default=None)
    """
    Position side
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
