# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_collateral_oco_order_response_stop_loss import CreateCollateralOcoOrderResponseStopLoss
from .create_collateral_oco_order_response_take_profit import CreateCollateralOcoOrderResponseTakeProfit


class CreateCollateralOcoOrderResponse(UniversalBaseModel):
    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    OCO order identifier
    """

    stop_loss: typing.Optional[CreateCollateralOcoOrderResponseStopLoss] = pydantic.Field(default=None)
    """
    Stop loss order details
    """

    take_profit: typing.Optional[CreateCollateralOcoOrderResponseTakeProfit] = pydantic.Field(default=None)
    """
    Take profit order details
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
