# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class CreateCollateralStopLimitOrderResponseOto(UniversalBaseModel):
    """
    OTO order data when stopLoss or takeProfit is specified
    """

    oto_id: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="otoId")] = pydantic.Field(
        default=None
    )
    """
    OTO order identifier
    """

    stop_loss: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="stopLoss")] = pydantic.Field(
        default=None
    )
    """
    Stop loss order price
    """

    take_profit: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="takeProfit")] = pydantic.Field(
        default=None
    )
    """
    Take profit order price
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
