# This file was auto-generated by Fern from our API Definition.

import typing

CreateCollateralTriggerMarketOrderResponsePositionSide = typing.Union[
    typing.Literal["LONG", "SHORT", "BOTH"], typing.Any
]
