# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_conditional_orders_response_records_item_oto_conditional_order_position_side import (
    GetConditionalOrdersResponseRecordsItemOtoConditionalOrderPositionSide,
)


class GetConditionalOrdersResponseRecordsItemOtoConditionalOrder(UniversalBaseModel):
    order_id: typing.Optional[int] = None
    client_order_id: typing.Optional[str] = None
    market: typing.Optional[str] = None
    position_side: typing_extensions.Annotated[
        typing.Optional[GetConditionalOrdersResponseRecordsItemOtoConditionalOrderPositionSide],
        FieldMetadata(alias="positionSide"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
