# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_funding_history_response_records_item import GetFundingHistoryResponseRecordsItem


class GetFundingHistoryResponse(UniversalBaseModel):
    records: typing.Optional[typing.List[GetFundingHistoryResponseRecordsItem]] = pydantic.Field(default=None)
    """
    Array of funding history entries
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of records per page
    """

    offset: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of records skipped
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
