# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetPositionsHistoryResponseItemOrderDetail(UniversalBaseModel):
    """
    Details of order which changes position
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Order identifier
    """

    trade_amount: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="tradeAmount")] = (
        pydantic.Field(default=None)
    )
    """
    Trade amount of order
    """

    price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order price
    """

    trade_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="tradeFee")] = pydantic.Field(
        default=None
    )
    """
    Order trade fee
    """

    funding_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fundingFee")] = pydantic.Field(
        default=None
    )
    """
    Funding fee captured by this position change
    """

    realized_pnl: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="realizedPnl")] = (
        pydantic.Field(default=None)
    )
    """
    Realized profit and loss
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
