# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_oco_orders_response_item_stop_loss_activation_condition import (
    GetOcoOrdersResponseItemStopLossActivationCondition,
)
from .get_oco_orders_response_item_stop_loss_side import GetOcoOrdersResponseItemStopLossSide


class GetOcoOrdersResponseItemStopLoss(UniversalBaseModel):
    """
    Stop loss order details
    """

    order_id: typing.Optional[int] = None
    client_order_id: typing.Optional[str] = None
    market: typing.Optional[str] = None
    side: typing.Optional[GetOcoOrdersResponseItemStopLossSide] = None
    type: typing.Optional[str] = None
    timestamp: typing.Optional[float] = None
    deal_money: typing.Optional[str] = None
    deal_stock: typing.Optional[str] = None
    amount: typing.Optional[str] = None
    taker_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="takerFee")] = None
    maker_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="makerFee")] = None
    left: typing.Optional[str] = None
    deal_fee: typing.Optional[str] = None
    post_only: typing.Optional[bool] = None
    mtime: typing.Optional[float] = None
    price: typing.Optional[str] = None
    activation_price: typing.Optional[str] = None
    activation_condition: typing.Optional[GetOcoOrdersResponseItemStopLossActivationCondition] = None
    activated: typing.Optional[int] = None
    status: typing.Optional[str] = None
    stp: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
