# This file was auto-generated by Fern from our API Definition.

import typing

GetPositionsHistoryResponseItemLiquidationState = typing.Union[typing.Literal["margin_call", "liquidation"], typing.Any]
