# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetFundingHistoryResponseRecordsItem(UniversalBaseModel):
    market: typing.Optional[str] = pydantic.Field(default=None)
    """
    Market name
    """

    funding_time: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fundingTime")] = (
        pydantic.Field(default=None)
    )
    """
    Funding time in Unix timestamp format
    """

    funding_rate: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fundingRate")] = (
        pydantic.Field(default=None)
    )
    """
    Funding rate applied
    """

    funding_amount: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fundingAmount")] = (
        pydantic.Field(default=None)
    )
    """
    Funding amount paid or received
    """

    position_amount: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="positionAmount")] = (
        pydantic.Field(default=None)
    )
    """
    Position amount at funding time
    """

    settlement_price: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="settlementPrice")] = (
        pydantic.Field(default=None)
    )
    """
    Settlement price used for funding calculation
    """

    rate_calculated_time: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="rateCalculatedTime")
    ] = pydantic.Field(default=None)
    """
    Time when the funding rate was calculated in Unix timestamp format
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
