# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.asset import Asset
from ..types.orderbook_response import OrderbookResponse
from .raw_client import AsyncRawPublicApiV4Client, RawPublicApiV4Client
from .types.get_api_v4public_collateral_markets_response import GetApiV4PublicCollateralMarketsResponse
from .types.get_api_v4public_funding_history_market_response_item import GetApiV4PublicFundingHistoryMarketResponseItem
from .types.get_api_v4public_futures_response import GetApiV4PublicFuturesResponse
from .types.get_api_v4public_markets_response_item import GetApiV4PublicMarketsResponseItem
from .types.get_api_v4public_mining_pool_response import GetApiV4PublicMiningPoolResponse
from .types.get_api_v4public_platform_status_response import GetApiV4PublicPlatformStatusResponse
from .types.get_api_v4public_ticker_response_value import GetApiV4PublicTickerResponseValue
from .types.get_api_v4public_time_response import GetApiV4PublicTimeResponse
from .types.get_api_v4public_trades_market_request_type import GetApiV4PublicTradesMarketRequestType
from .types.get_api_v4public_trades_market_response_item import GetApiV4PublicTradesMarketResponseItem


class PublicApiV4Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPublicApiV4Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPublicApiV4Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPublicApiV4Client
        """
        return self._raw_client

    def maintenance_status(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicPlatformStatusResponse:
        """
        The endpoint retrieves maintenance status

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicPlatformStatusResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.maintenance_status()
        """
        _response = self._raw_client.maintenance_status(request_options=request_options)
        return _response.data

    def market_info(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GetApiV4PublicMarketsResponseItem]:
        """
        The endpoint retrieves all information about available spot and futures markets.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetApiV4PublicMarketsResponseItem]
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.market_info()
        """
        _response = self._raw_client.market_info(request_options=request_options)
        return _response.data

    def market_activity(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, GetApiV4PublicTickerResponseValue]:
        """
        The endpoint retrieves a 24-hour pricing and volume summary for each market pair available on the exchange.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, GetApiV4PublicTickerResponseValue]
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.market_activity()
        """
        _response = self._raw_client.market_activity(request_options=request_options)
        return _response.data

    def asset_status_list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Dict[str, Asset]:
        """
        The endpoint retrieves the assets status.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, Asset]
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.asset_status_list()
        """
        _response = self._raw_client.asset_status_list(request_options=request_options)
        return _response.data

    def orderbook(
        self,
        market: str,
        *,
        limit: typing.Optional[int] = None,
        level: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderbookResponse:
        """
        The endpoint retrieves the current [order book](/glossary#order-book) as two arrays ([bids](/glossary#bid) / [asks](/glossary#ask)) with additional parameters.

        <Note>
        The API caches the response for 100 ms
        </Note>

        <Warning>
        Rate limit 600 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        limit : typing.Optional[int]
            Orders depth quantity: 0 - 100. Not defined or 0 will return 100 entries.

        level : typing.Optional[int]
            Optional parameter that controls the aggregation level. Level 0 – default, no aggregation. Levels 1–5 provide increasing aggregation of the order book.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderbookResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.orderbook(market='BTC_USDT', limit=100, level=2, )
        """
        _response = self._raw_client.orderbook(market, limit=limit, level=level, request_options=request_options)
        return _response.data

    def depth(self, market: str, *, request_options: typing.Optional[RequestOptions] = None) -> OrderbookResponse:
        """
        The endpoint retrieves depth price levels within ±2% of the market last price. Use when lightweight order book data is needed for a narrow price band around the current market price. The ±2% constraint limits the response to price levels near the last traded price, reducing payload size compared to the full order book.

        <Note>
        The API caches the response for 1 sec
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderbookResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.depth(market='BTC_USDT', )
        """
        _response = self._raw_client.depth(market, request_options=request_options)
        return _response.data

    def recent_trades(
        self,
        market: str,
        *,
        type: typing.Optional[GetApiV4PublicTradesMarketRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[GetApiV4PublicTradesMarketResponseItem]:
        """
        The endpoint retrieves the [trades](/glossary#deal-trade) that have been executed recently on the requested [market](/glossary#market).

        <Note>
        The API caches the response for 1 second
        </Note>

        <Note>
          Public trade data can include executions that originate from RPI orders. Public order book feeds (`depth`, `bookTicker`) exclude RPI orders. RPI orders appear only in private active orders and in the exchange UI order book (web and mobile).
        </Note>


        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        type : typing.Optional[GetApiV4PublicTradesMarketRequestType]
            Can be buy or sell

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetApiV4PublicTradesMarketResponseItem]
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.recent_trades(market='BTC_USDT', )
        """
        _response = self._raw_client.recent_trades(market, type=type, request_options=request_options)
        return _response.data

    def fee(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint retrieves the list of [fees](/glossary#fee) and min/max amounts for deposits and withdrawals

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.fee()
        """
        _response = self._raw_client.fee(request_options=request_options)
        return _response.data

    def server_time(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetApiV4PublicTimeResponse:
        """
        The endpoint retrieves the current server time.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicTimeResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.server_time()
        """
        _response = self._raw_client.server_time(request_options=request_options)
        return _response.data

    def server_status(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[str]:
        """
        The endpoint retrieves the current API life-state.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.server_status()
        """
        _response = self._raw_client.server_status(request_options=request_options)
        return _response.data

    def collateral_markets_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicCollateralMarketsResponse:
        """
        The endpoint returns the list of [markets](/glossary#market) that are available for [collateral](/glossary#collateral) trading

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicCollateralMarketsResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.collateral_markets_list()
        """
        _response = self._raw_client.collateral_markets_list(request_options=request_options)
        return _response.data

    def available_futures_markets_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicFuturesResponse:
        """
        The endpoint returns the list of available futures markets.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicFuturesResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.available_futures_markets_list()
        """
        _response = self._raw_client.available_futures_markets_list(request_options=request_options)
        return _response.data

    def funding_history(
        self,
        market: str,
        *,
        start_date: typing.Optional[int] = None,
        end_date: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[GetApiV4PublicFundingHistoryMarketResponseItem]:
        """
        The endpoint returns the funding rate history for a specified futures market.

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market name (e.g., BTC_PERP)

        start_date : typing.Optional[int]
            Start timestamp in seconds

        end_date : typing.Optional[int]
            End timestamp in seconds

        limit : typing.Optional[int]
            Number of records to return. Default: 100, Maximum: 1000

        offset : typing.Optional[int]
            Number of records to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetApiV4PublicFundingHistoryMarketResponseItem]
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.funding_history(market='BTC_PERP', start_date=1752480000, end_date=1752537600, limit=100, offset=0, )
        """
        _response = self._raw_client.funding_history(
            market,
            start_date=start_date,
            end_date=end_date,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    def mining_pool_overview(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicMiningPoolResponse:
        """
        The endpoint returns overall information about the current mining pool state.

        Hash rate is expressed in H units.

        <Warning>
        Rate limit 1000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicMiningPoolResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.public_api_v4.mining_pool_overview()
        """
        _response = self._raw_client.mining_pool_overview(request_options=request_options)
        return _response.data


class AsyncPublicApiV4Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPublicApiV4Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPublicApiV4Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPublicApiV4Client
        """
        return self._raw_client

    async def maintenance_status(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicPlatformStatusResponse:
        """
        The endpoint retrieves maintenance status

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicPlatformStatusResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.maintenance_status()
        asyncio.run(main())
        """
        _response = await self._raw_client.maintenance_status(request_options=request_options)
        return _response.data

    async def market_info(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GetApiV4PublicMarketsResponseItem]:
        """
        The endpoint retrieves all information about available spot and futures markets.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetApiV4PublicMarketsResponseItem]
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.market_info()
        asyncio.run(main())
        """
        _response = await self._raw_client.market_info(request_options=request_options)
        return _response.data

    async def market_activity(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, GetApiV4PublicTickerResponseValue]:
        """
        The endpoint retrieves a 24-hour pricing and volume summary for each market pair available on the exchange.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, GetApiV4PublicTickerResponseValue]
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.market_activity()
        asyncio.run(main())
        """
        _response = await self._raw_client.market_activity(request_options=request_options)
        return _response.data

    async def asset_status_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, Asset]:
        """
        The endpoint retrieves the assets status.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, Asset]
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.asset_status_list()
        asyncio.run(main())
        """
        _response = await self._raw_client.asset_status_list(request_options=request_options)
        return _response.data

    async def orderbook(
        self,
        market: str,
        *,
        limit: typing.Optional[int] = None,
        level: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderbookResponse:
        """
        The endpoint retrieves the current [order book](/glossary#order-book) as two arrays ([bids](/glossary#bid) / [asks](/glossary#ask)) with additional parameters.

        <Note>
        The API caches the response for 100 ms
        </Note>

        <Warning>
        Rate limit 600 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        limit : typing.Optional[int]
            Orders depth quantity: 0 - 100. Not defined or 0 will return 100 entries.

        level : typing.Optional[int]
            Optional parameter that controls the aggregation level. Level 0 – default, no aggregation. Levels 1–5 provide increasing aggregation of the order book.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderbookResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.orderbook(market='BTC_USDT', limit=100, level=2, )
        asyncio.run(main())
        """
        _response = await self._raw_client.orderbook(market, limit=limit, level=level, request_options=request_options)
        return _response.data

    async def depth(self, market: str, *, request_options: typing.Optional[RequestOptions] = None) -> OrderbookResponse:
        """
        The endpoint retrieves depth price levels within ±2% of the market last price. Use when lightweight order book data is needed for a narrow price band around the current market price. The ±2% constraint limits the response to price levels near the last traded price, reducing payload size compared to the full order book.

        <Note>
        The API caches the response for 1 sec
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderbookResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.depth(market='BTC_USDT', )
        asyncio.run(main())
        """
        _response = await self._raw_client.depth(market, request_options=request_options)
        return _response.data

    async def recent_trades(
        self,
        market: str,
        *,
        type: typing.Optional[GetApiV4PublicTradesMarketRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[GetApiV4PublicTradesMarketResponseItem]:
        """
        The endpoint retrieves the [trades](/glossary#deal-trade) that have been executed recently on the requested [market](/glossary#market).

        <Note>
        The API caches the response for 1 second
        </Note>

        <Note>
          Public trade data can include executions that originate from RPI orders. Public order book feeds (`depth`, `bookTicker`) exclude RPI orders. RPI orders appear only in private active orders and in the exchange UI order book (web and mobile).
        </Note>


        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        type : typing.Optional[GetApiV4PublicTradesMarketRequestType]
            Can be buy or sell

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetApiV4PublicTradesMarketResponseItem]
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.recent_trades(market='BTC_USDT', )
        asyncio.run(main())
        """
        _response = await self._raw_client.recent_trades(market, type=type, request_options=request_options)
        return _response.data

    async def fee(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        The endpoint retrieves the list of [fees](/glossary#fee) and min/max amounts for deposits and withdrawals

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.fee()
        asyncio.run(main())
        """
        _response = await self._raw_client.fee(request_options=request_options)
        return _response.data

    async def server_time(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicTimeResponse:
        """
        The endpoint retrieves the current server time.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicTimeResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.server_time()
        asyncio.run(main())
        """
        _response = await self._raw_client.server_time(request_options=request_options)
        return _response.data

    async def server_status(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[str]:
        """
        The endpoint retrieves the current API life-state.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.server_status()
        asyncio.run(main())
        """
        _response = await self._raw_client.server_status(request_options=request_options)
        return _response.data

    async def collateral_markets_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicCollateralMarketsResponse:
        """
        The endpoint returns the list of [markets](/glossary#market) that are available for [collateral](/glossary#collateral) trading

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicCollateralMarketsResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.collateral_markets_list()
        asyncio.run(main())
        """
        _response = await self._raw_client.collateral_markets_list(request_options=request_options)
        return _response.data

    async def available_futures_markets_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicFuturesResponse:
        """
        The endpoint returns the list of available futures markets.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicFuturesResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.available_futures_markets_list()
        asyncio.run(main())
        """
        _response = await self._raw_client.available_futures_markets_list(request_options=request_options)
        return _response.data

    async def funding_history(
        self,
        market: str,
        *,
        start_date: typing.Optional[int] = None,
        end_date: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[GetApiV4PublicFundingHistoryMarketResponseItem]:
        """
        The endpoint returns the funding rate history for a specified futures market.

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market name (e.g., BTC_PERP)

        start_date : typing.Optional[int]
            Start timestamp in seconds

        end_date : typing.Optional[int]
            End timestamp in seconds

        limit : typing.Optional[int]
            Number of records to return. Default: 100, Maximum: 1000

        offset : typing.Optional[int]
            Number of records to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetApiV4PublicFundingHistoryMarketResponseItem]
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.funding_history(market='BTC_PERP', start_date=1752480000, end_date=1752537600, limit=100, offset=0, )
        asyncio.run(main())
        """
        _response = await self._raw_client.funding_history(
            market,
            start_date=start_date,
            end_date=end_date,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    async def mining_pool_overview(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV4PublicMiningPoolResponse:
        """
        The endpoint returns overall information about the current mining pool state.

        Hash rate is expressed in H units.

        <Warning>
        Rate limit 1000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV4PublicMiningPoolResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.public_api_v4.mining_pool_overview()
        asyncio.run(main())
        """
        _response = await self._raw_client.mining_pool_overview(request_options=request_options)
        return _response.data
