# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.asset import Asset
from ..types.orderbook_response import OrderbookResponse
from .types.get_api_v4public_collateral_markets_response import GetApiV4PublicCollateralMarketsResponse
from .types.get_api_v4public_funding_history_market_response_item import GetApiV4PublicFundingHistoryMarketResponseItem
from .types.get_api_v4public_futures_response import GetApiV4PublicFuturesResponse
from .types.get_api_v4public_markets_response_item import GetApiV4PublicMarketsResponseItem
from .types.get_api_v4public_mining_pool_response import GetApiV4PublicMiningPoolResponse
from .types.get_api_v4public_platform_status_response import GetApiV4PublicPlatformStatusResponse
from .types.get_api_v4public_ticker_response_value import GetApiV4PublicTickerResponseValue
from .types.get_api_v4public_time_response import GetApiV4PublicTimeResponse
from .types.get_api_v4public_trades_market_request_type import GetApiV4PublicTradesMarketRequestType
from .types.get_api_v4public_trades_market_response_item import GetApiV4PublicTradesMarketResponseItem


class RawPublicApiV4Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def maintenance_status(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetApiV4PublicPlatformStatusResponse]:
        """
        The endpoint retrieves maintenance status

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetApiV4PublicPlatformStatusResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/platform/status",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicPlatformStatusResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicPlatformStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def market_info(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[GetApiV4PublicMarketsResponseItem]]:
        """
        The endpoint retrieves all information about available spot and futures markets.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[GetApiV4PublicMarketsResponseItem]]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/markets",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GetApiV4PublicMarketsResponseItem],
                    parse_obj_as(
                        type_=typing.List[GetApiV4PublicMarketsResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def market_activity(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Dict[str, GetApiV4PublicTickerResponseValue]]:
        """
        The endpoint retrieves a 24-hour pricing and volume summary for each market pair available on the exchange.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Dict[str, GetApiV4PublicTickerResponseValue]]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/ticker",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, GetApiV4PublicTickerResponseValue],
                    parse_obj_as(
                        type_=typing.Dict[str, GetApiV4PublicTickerResponseValue],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def asset_status_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Dict[str, Asset]]:
        """
        The endpoint retrieves the assets status.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Dict[str, Asset]]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/assets",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, Asset],
                    parse_obj_as(
                        type_=typing.Dict[str, Asset],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def orderbook(
        self,
        market: str,
        *,
        limit: typing.Optional[int] = None,
        level: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OrderbookResponse]:
        """
        The endpoint retrieves the current [order book](/glossary#order-book) as two arrays ([bids](/glossary#bid) / [asks](/glossary#ask)) with additional parameters.

        <Note>
        The API caches the response for 100 ms
        </Note>

        <Warning>
        Rate limit 600 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        limit : typing.Optional[int]
            Orders depth quantity: 0 - 100. Not defined or 0 will return 100 entries.

        level : typing.Optional[int]
            Optional parameter that controls the aggregation level. Level 0 – default, no aggregation. Levels 1–5 provide increasing aggregation of the order book.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrderbookResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v4/public/orderbook/{jsonable_encoder(market)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "limit": limit,
                "level": level,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderbookResponse,
                    parse_obj_as(
                        type_=OrderbookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def depth(
        self, market: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OrderbookResponse]:
        """
        The endpoint retrieves depth price levels within ±2% of the market last price. Use when lightweight order book data is needed for a narrow price band around the current market price. The ±2% constraint limits the response to price levels near the last traded price, reducing payload size compared to the full order book.

        <Note>
        The API caches the response for 1 sec
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrderbookResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v4/public/orderbook/depth/{jsonable_encoder(market)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderbookResponse,
                    parse_obj_as(
                        type_=OrderbookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def recent_trades(
        self,
        market: str,
        *,
        type: typing.Optional[GetApiV4PublicTradesMarketRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[GetApiV4PublicTradesMarketResponseItem]]:
        """
        The endpoint retrieves the [trades](/glossary#deal-trade) that have been executed recently on the requested [market](/glossary#market).

        <Note>
        The API caches the response for 1 second
        </Note>

        <Note>
          Public trade data can include executions that originate from RPI orders. Public order book feeds (`depth`, `bookTicker`) exclude RPI orders. RPI orders appear only in private active orders and in the exchange UI order book (web and mobile).
        </Note>


        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        type : typing.Optional[GetApiV4PublicTradesMarketRequestType]
            Can be buy or sell

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[GetApiV4PublicTradesMarketResponseItem]]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v4/public/trades/{jsonable_encoder(market)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "type": type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GetApiV4PublicTradesMarketResponseItem],
                    parse_obj_as(
                        type_=typing.List[GetApiV4PublicTradesMarketResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def fee(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Dict[str, typing.Optional[typing.Any]]]:
        """
        The endpoint retrieves the list of [fees](/glossary#fee) and min/max amounts for deposits and withdrawals

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Dict[str, typing.Optional[typing.Any]]]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/fee",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, typing.Optional[typing.Any]],
                    parse_obj_as(
                        type_=typing.Dict[str, typing.Optional[typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def server_time(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetApiV4PublicTimeResponse]:
        """
        The endpoint retrieves the current server time.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetApiV4PublicTimeResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/time",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicTimeResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicTimeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def server_status(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[str]]:
        """
        The endpoint retrieves the current API life-state.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[str]]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/ping",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[str],
                    parse_obj_as(
                        type_=typing.List[str],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def collateral_markets_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetApiV4PublicCollateralMarketsResponse]:
        """
        The endpoint returns the list of [markets](/glossary#market) that are available for [collateral](/glossary#collateral) trading

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetApiV4PublicCollateralMarketsResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/collateral/markets",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicCollateralMarketsResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicCollateralMarketsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def available_futures_markets_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetApiV4PublicFuturesResponse]:
        """
        The endpoint returns the list of available futures markets.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetApiV4PublicFuturesResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/futures",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicFuturesResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicFuturesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def funding_history(
        self,
        market: str,
        *,
        start_date: typing.Optional[int] = None,
        end_date: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[GetApiV4PublicFundingHistoryMarketResponseItem]]:
        """
        The endpoint returns the funding rate history for a specified futures market.

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market name (e.g., BTC_PERP)

        start_date : typing.Optional[int]
            Start timestamp in seconds

        end_date : typing.Optional[int]
            End timestamp in seconds

        limit : typing.Optional[int]
            Number of records to return. Default: 100, Maximum: 1000

        offset : typing.Optional[int]
            Number of records to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[GetApiV4PublicFundingHistoryMarketResponseItem]]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v4/public/funding-history/{jsonable_encoder(market)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startDate": start_date,
                "endDate": end_date,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GetApiV4PublicFundingHistoryMarketResponseItem],
                    parse_obj_as(
                        type_=typing.List[GetApiV4PublicFundingHistoryMarketResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mining_pool_overview(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetApiV4PublicMiningPoolResponse]:
        """
        The endpoint returns overall information about the current mining pool state.

        Hash rate is expressed in H units.

        <Warning>
        Rate limit 1000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetApiV4PublicMiningPoolResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/public/mining-pool",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicMiningPoolResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicMiningPoolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPublicApiV4Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def maintenance_status(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetApiV4PublicPlatformStatusResponse]:
        """
        The endpoint retrieves maintenance status

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetApiV4PublicPlatformStatusResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/platform/status",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicPlatformStatusResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicPlatformStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def market_info(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[GetApiV4PublicMarketsResponseItem]]:
        """
        The endpoint retrieves all information about available spot and futures markets.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[GetApiV4PublicMarketsResponseItem]]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/markets",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GetApiV4PublicMarketsResponseItem],
                    parse_obj_as(
                        type_=typing.List[GetApiV4PublicMarketsResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def market_activity(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Dict[str, GetApiV4PublicTickerResponseValue]]:
        """
        The endpoint retrieves a 24-hour pricing and volume summary for each market pair available on the exchange.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Dict[str, GetApiV4PublicTickerResponseValue]]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/ticker",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, GetApiV4PublicTickerResponseValue],
                    parse_obj_as(
                        type_=typing.Dict[str, GetApiV4PublicTickerResponseValue],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def asset_status_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Dict[str, Asset]]:
        """
        The endpoint retrieves the assets status.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Dict[str, Asset]]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/assets",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, Asset],
                    parse_obj_as(
                        type_=typing.Dict[str, Asset],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def orderbook(
        self,
        market: str,
        *,
        limit: typing.Optional[int] = None,
        level: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OrderbookResponse]:
        """
        The endpoint retrieves the current [order book](/glossary#order-book) as two arrays ([bids](/glossary#bid) / [asks](/glossary#ask)) with additional parameters.

        <Note>
        The API caches the response for 100 ms
        </Note>

        <Warning>
        Rate limit 600 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        limit : typing.Optional[int]
            Orders depth quantity: 0 - 100. Not defined or 0 will return 100 entries.

        level : typing.Optional[int]
            Optional parameter that controls the aggregation level. Level 0 – default, no aggregation. Levels 1–5 provide increasing aggregation of the order book.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrderbookResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v4/public/orderbook/{jsonable_encoder(market)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "limit": limit,
                "level": level,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderbookResponse,
                    parse_obj_as(
                        type_=OrderbookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def depth(
        self, market: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OrderbookResponse]:
        """
        The endpoint retrieves depth price levels within ±2% of the market last price. Use when lightweight order book data is needed for a narrow price band around the current market price. The ±2% constraint limits the response to price levels near the last traded price, reducing payload size compared to the full order book.

        <Note>
        The API caches the response for 1 sec
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrderbookResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v4/public/orderbook/depth/{jsonable_encoder(market)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderbookResponse,
                    parse_obj_as(
                        type_=OrderbookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def recent_trades(
        self,
        market: str,
        *,
        type: typing.Optional[GetApiV4PublicTradesMarketRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[GetApiV4PublicTradesMarketResponseItem]]:
        """
        The endpoint retrieves the [trades](/glossary#deal-trade) that have been executed recently on the requested [market](/glossary#market).

        <Note>
        The API caches the response for 1 second
        </Note>

        <Note>
          Public trade data can include executions that originate from RPI orders. Public order book feeds (`depth`, `bookTicker`) exclude RPI orders. RPI orders appear only in private active orders and in the exchange UI order book (web and mobile).
        </Note>


        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market pair name

        type : typing.Optional[GetApiV4PublicTradesMarketRequestType]
            Can be buy or sell

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[GetApiV4PublicTradesMarketResponseItem]]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v4/public/trades/{jsonable_encoder(market)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "type": type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GetApiV4PublicTradesMarketResponseItem],
                    parse_obj_as(
                        type_=typing.List[GetApiV4PublicTradesMarketResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def fee(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Dict[str, typing.Optional[typing.Any]]]:
        """
        The endpoint retrieves the list of [fees](/glossary#fee) and min/max amounts for deposits and withdrawals

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Dict[str, typing.Optional[typing.Any]]]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/fee",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, typing.Optional[typing.Any]],
                    parse_obj_as(
                        type_=typing.Dict[str, typing.Optional[typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def server_time(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetApiV4PublicTimeResponse]:
        """
        The endpoint retrieves the current server time.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetApiV4PublicTimeResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/time",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicTimeResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicTimeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def server_status(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[str]]:
        """
        The endpoint retrieves the current API life-state.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[str]]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/ping",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[str],
                    parse_obj_as(
                        type_=typing.List[str],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def collateral_markets_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetApiV4PublicCollateralMarketsResponse]:
        """
        The endpoint returns the list of [markets](/glossary#market) that are available for [collateral](/glossary#collateral) trading

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetApiV4PublicCollateralMarketsResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/collateral/markets",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicCollateralMarketsResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicCollateralMarketsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def available_futures_markets_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetApiV4PublicFuturesResponse]:
        """
        The endpoint returns the list of available futures markets.

        <Note>
        The API caches the response for 1 second
        </Note>

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetApiV4PublicFuturesResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/futures",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicFuturesResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicFuturesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def funding_history(
        self,
        market: str,
        *,
        start_date: typing.Optional[int] = None,
        end_date: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[GetApiV4PublicFundingHistoryMarketResponseItem]]:
        """
        The endpoint returns the funding rate history for a specified futures market.

        <Warning>
        Rate limit 2000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        market : str
            Market name (e.g., BTC_PERP)

        start_date : typing.Optional[int]
            Start timestamp in seconds

        end_date : typing.Optional[int]
            End timestamp in seconds

        limit : typing.Optional[int]
            Number of records to return. Default: 100, Maximum: 1000

        offset : typing.Optional[int]
            Number of records to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[GetApiV4PublicFundingHistoryMarketResponseItem]]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v4/public/funding-history/{jsonable_encoder(market)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startDate": start_date,
                "endDate": end_date,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GetApiV4PublicFundingHistoryMarketResponseItem],
                    parse_obj_as(
                        type_=typing.List[GetApiV4PublicFundingHistoryMarketResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mining_pool_overview(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetApiV4PublicMiningPoolResponse]:
        """
        The endpoint returns overall information about the current mining pool state.

        Hash rate is expressed in H units.

        <Warning>
        Rate limit 1000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetApiV4PublicMiningPoolResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/public/mining-pool",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetApiV4PublicMiningPoolResponse,
                    parse_obj_as(
                        type_=GetApiV4PublicMiningPoolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
