# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.code_info import CodeInfo


class GetMyCodesResponse(UniversalBaseModel):
    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of codes
    """

    data: typing.Optional[typing.List[CodeInfo]] = None
    limit: typing.Optional[int] = None
    offset: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
