# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.http_response import AsyncHttpResponse, HttpResponse
from .core.pydantic_utilities import parse_obj_as
from .core.request_options import RequestOptions
from .errors.bad_request_error import BadRequestError
from .errors.unprocessable_entity_error import UnprocessableEntityError
from .types.convert_confirm_response import ConvertConfirmResponse
from .types.convert_estimate_request_direction import ConvertEstimateRequestDirection
from .types.convert_estimate_response import ConvertEstimateResponse
from .types.convert_history_response import ConvertHistoryResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWhitebitApi:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def convert_estimate(
        self,
        *,
        from_: str,
        to: str,
        direction: ConvertEstimateRequestDirection,
        amount: str,
        nonce: typing.Optional[int] = OMIT,
        request: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ConvertEstimateResponse]:
        """
        The endpoint creates a quote for converting one currency to another. Quote lifetime is 10 seconds, then quote will be expired.

        <Warning>
        Rate limit: 10000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        from_ : str
            From currency. Example: BTC

        to : str
            To currency. Example: USDT

        direction : ConvertEstimateRequestDirection
            Convert amount direction, defines in which currency corresponding "amount" field is populated. Use "to" in case amount is in "to" currency, use "from" if amount is in "from" currency

        amount : str
            Amount to convert or receive.

        nonce : typing.Optional[int]
            Nonce for request

        request : typing.Optional[str]
            Request path

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ConvertEstimateResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/convert/estimate",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "from": from_,
                "to": to,
                "direction": direction,
                "amount": amount,
                "nonce": nonce,
                "request": request,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConvertEstimateResponse,
                    parse_obj_as(
                        type_=ConvertEstimateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def convert_confirm(
        self,
        *,
        quote_id: str,
        nonce: typing.Optional[int] = OMIT,
        request: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ConvertConfirmResponse]:
        """
        The endpoint confirms an estimated quote.

        <Warning>
        Rate limit: 10000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        quote_id : str
            Quote ID

        nonce : typing.Optional[int]
            Nonce for request

        request : typing.Optional[str]
            Request path

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ConvertConfirmResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/convert/confirm",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "quoteId": quote_id,
                "nonce": nonce,
                "request": request,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConvertConfirmResponse,
                    parse_obj_as(
                        type_=ConvertConfirmResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def convert_history(
        self,
        *,
        from_ticker: typing.Optional[str] = OMIT,
        to_ticker: typing.Optional[str] = OMIT,
        from_: typing.Optional[str] = OMIT,
        to: typing.Optional[str] = OMIT,
        quote_id: typing.Optional[str] = OMIT,
        limit: typing.Optional[str] = OMIT,
        offset: typing.Optional[str] = OMIT,
        nonce: typing.Optional[int] = OMIT,
        request: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ConvertHistoryResponse]:
        """
        The endpoint returns convert history.

        <Warning>
        Rate limit: 10000 requests/10 sec.
        </Warning>
        **Note:** The endpoint can retrieve data not older than 6 months from current month. For older data, use the Report on the History page.

        Parameters
        ----------
        from_ticker : typing.Optional[str]
            From currency. Example: BTC

        to_ticker : typing.Optional[str]
            To currency. Example: USDT

        from_ : typing.Optional[str]
            From time filter. Example: 1699260637. Default: now()

        to : typing.Optional[str]
            To time filter. Example: 1699260637. Default: now() +

        quote_id : typing.Optional[str]
            Quote Id. Example: 4050

        limit : typing.Optional[str]
            How many records to receive. Default: 100

        offset : typing.Optional[str]
            Amount to convert or receive. Default 0

        nonce : typing.Optional[int]
            Nonce for request

        request : typing.Optional[str]
            Request path

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ConvertHistoryResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/convert/history",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "fromTicker": from_ticker,
                "toTicker": to_ticker,
                "from": from_,
                "to": to,
                "quoteId": quote_id,
                "limit": limit,
                "offset": offset,
                "nonce": nonce,
                "request": request,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConvertHistoryResponse,
                    parse_obj_as(
                        type_=ConvertHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWhitebitApi:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def convert_estimate(
        self,
        *,
        from_: str,
        to: str,
        direction: ConvertEstimateRequestDirection,
        amount: str,
        nonce: typing.Optional[int] = OMIT,
        request: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ConvertEstimateResponse]:
        """
        The endpoint creates a quote for converting one currency to another. Quote lifetime is 10 seconds, then quote will be expired.

        <Warning>
        Rate limit: 10000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        from_ : str
            From currency. Example: BTC

        to : str
            To currency. Example: USDT

        direction : ConvertEstimateRequestDirection
            Convert amount direction, defines in which currency corresponding "amount" field is populated. Use "to" in case amount is in "to" currency, use "from" if amount is in "from" currency

        amount : str
            Amount to convert or receive.

        nonce : typing.Optional[int]
            Nonce for request

        request : typing.Optional[str]
            Request path

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ConvertEstimateResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/convert/estimate",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "from": from_,
                "to": to,
                "direction": direction,
                "amount": amount,
                "nonce": nonce,
                "request": request,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConvertEstimateResponse,
                    parse_obj_as(
                        type_=ConvertEstimateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def convert_confirm(
        self,
        *,
        quote_id: str,
        nonce: typing.Optional[int] = OMIT,
        request: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ConvertConfirmResponse]:
        """
        The endpoint confirms an estimated quote.

        <Warning>
        Rate limit: 10000 requests/10 sec.
        </Warning>

        Parameters
        ----------
        quote_id : str
            Quote ID

        nonce : typing.Optional[int]
            Nonce for request

        request : typing.Optional[str]
            Request path

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ConvertConfirmResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/convert/confirm",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "quoteId": quote_id,
                "nonce": nonce,
                "request": request,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConvertConfirmResponse,
                    parse_obj_as(
                        type_=ConvertConfirmResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def convert_history(
        self,
        *,
        from_ticker: typing.Optional[str] = OMIT,
        to_ticker: typing.Optional[str] = OMIT,
        from_: typing.Optional[str] = OMIT,
        to: typing.Optional[str] = OMIT,
        quote_id: typing.Optional[str] = OMIT,
        limit: typing.Optional[str] = OMIT,
        offset: typing.Optional[str] = OMIT,
        nonce: typing.Optional[int] = OMIT,
        request: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ConvertHistoryResponse]:
        """
        The endpoint returns convert history.

        <Warning>
        Rate limit: 10000 requests/10 sec.
        </Warning>
        **Note:** The endpoint can retrieve data not older than 6 months from current month. For older data, use the Report on the History page.

        Parameters
        ----------
        from_ticker : typing.Optional[str]
            From currency. Example: BTC

        to_ticker : typing.Optional[str]
            To currency. Example: USDT

        from_ : typing.Optional[str]
            From time filter. Example: 1699260637. Default: now()

        to : typing.Optional[str]
            To time filter. Example: 1699260637. Default: now() +

        quote_id : typing.Optional[str]
            Quote Id. Example: 4050

        limit : typing.Optional[str]
            How many records to receive. Default: 100

        offset : typing.Optional[str]
            Amount to convert or receive. Default 0

        nonce : typing.Optional[int]
            Nonce for request

        request : typing.Optional[str]
            Request path

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ConvertHistoryResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/convert/history",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "fromTicker": from_ticker,
                "toTicker": to_ticker,
                "from": from_,
                "to": to,
                "quoteId": quote_id,
                "limit": limit,
                "offset": offset,
                "nonce": nonce,
                "request": request,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConvertHistoryResponse,
                    parse_obj_as(
                        type_=ConvertHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
