# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_order_history_response_value_item_side import GetOrderHistoryResponseValueItemSide


class GetOrderHistoryResponseValueItem(UniversalBaseModel):
    amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trade amount
    """

    price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order price
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order type
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Order identifier
    """

    client_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Custom order identifier. Empty string if not specified
    """

    side: typing.Optional[GetOrderHistoryResponseValueItemSide] = pydantic.Field(default=None)
    """
    Order side
    """

    ctime: typing.Optional[float] = pydantic.Field(default=None)
    """
    Timestamp of order creation
    """

    taker_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="takerFee")] = pydantic.Field(
        default=None
    )
    """
    Taker fee ratio. If the number less than 0.0001 - rounded to zero
    """

    ftime: typing.Optional[float] = pydantic.Field(default=None)
    """
    Executed order timestamp
    """

    maker_fee: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="makerFee")] = pydantic.Field(
        default=None
    )
    """
    Maker fee ratio. If the number less than 0.0001 - rounded to zero
    """

    deal_fee: typing.Optional[str] = pydantic.Field(default=None)
    """
    Paid fee when order is finished
    """

    deal_stock: typing.Optional[str] = pydantic.Field(default=None)
    """
    Amount in stock currency that finished
    """

    deal_money: typing.Optional[str] = pydantic.Field(default=None)
    """
    Amount in money currency that finished
    """

    post_only: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="postOnly")] = pydantic.Field(
        default=None
    )
    """
    Post-only flag
    """

    ioc: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Immediate or cancel flag
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order status
    """

    fee_asset: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="feeAsset")] = pydantic.Field(
        default=None
    )
    """
    Fee asset
    """

    stp: typing.Optional[str] = pydantic.Field(default=None)
    """
    Self trade prevention mode
    """

    rpi: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Retail Price Improvement flag
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
