# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_kill_switch_status_response_item_types_item import GetKillSwitchStatusResponseItemTypesItem


class GetKillSwitchStatusResponseItem(UniversalBaseModel):
    market: typing.Optional[str] = pydantic.Field(default=None)
    """
    Market name
    """

    start_time: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="startTime")] = pydantic.Field(
        default=None
    )
    """
    Timer start timestamp
    """

    cancellation_time: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="cancellationTime")] = (
        pydantic.Field(default=None)
    )
    """
    Order cancellation timestamp (startTime + timeout)
    """

    types: typing.Optional[typing.List[GetKillSwitchStatusResponseItemTypesItem]] = pydantic.Field(default=None)
    """
    Order types affected by kill-switch
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
