# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from .types.get_web_socket_token_response import GetWebSocketTokenResponse
from .types.issue_jwt_token_response import IssueJwtTokenResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawJwtClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def issue_jwt_token(
        self,
        *,
        request: str,
        nonce: str,
        nonce_window: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IssueJwtTokenResponse]:
        """
        The endpoint issues a JWT token for the Fiat Gateway service.
        The token is used to authenticate requests to the Fiat Gateway API.

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        nonce_window : typing.Optional[bool]
            Nonce window setting

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IssueJwtTokenResponse]
            Validation succeeded and JWT token is returned
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/jwt",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "request": request,
                "nonceWindow": nonce_window,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IssueJwtTokenResponse,
                    parse_obj_as(
                        type_=IssueJwtTokenResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_web_socket_token(
        self, *, request: str, nonce: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetWebSocketTokenResponse]:
        """
        The V4 endpoint can be used to retrieve the WebSocket token for user.
        The token is required to authorize WebSocket connections for private API access.

        <Warning>
        Rate limit: 10 requests/60 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetWebSocketTokenResponse]
            WebSocket token retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/profile/websocket_token",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWebSocketTokenResponse,
                    parse_obj_as(
                        type_=GetWebSocketTokenResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawJwtClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def issue_jwt_token(
        self,
        *,
        request: str,
        nonce: str,
        nonce_window: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IssueJwtTokenResponse]:
        """
        The endpoint issues a JWT token for the Fiat Gateway service.
        The token is used to authenticate requests to the Fiat Gateway API.

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        nonce_window : typing.Optional[bool]
            Nonce window setting

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IssueJwtTokenResponse]
            Validation succeeded and JWT token is returned
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/jwt",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "request": request,
                "nonceWindow": nonce_window,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IssueJwtTokenResponse,
                    parse_obj_as(
                        type_=IssueJwtTokenResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_web_socket_token(
        self, *, request: str, nonce: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetWebSocketTokenResponse]:
        """
        The V4 endpoint can be used to retrieve the WebSocket token for user.
        The token is required to authorize WebSocket connections for private API access.

        <Warning>
        Rate limit: 10 requests/60 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetWebSocketTokenResponse]
            WebSocket token retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/profile/websocket_token",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWebSocketTokenResponse,
                    parse_obj_as(
                        type_=GetWebSocketTokenResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
