# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from .types.get_deposit_withdraw_history_response import GetDepositWithdrawHistoryResponse
from .types.get_main_balance_response_value import GetMainBalanceResponseValue

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawMainAccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_main_balance(
        self,
        *,
        request: str,
        nonce: str,
        ticker: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Dict[str, GetMainBalanceResponseValue]]:
        """
        The endpoint retrieves the [main balance](/glossary#balance-main) by currency [ticker](/glossary#ticker) or all balances.

        <Warning>
          Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        ticker : typing.Optional[str]
            Currency's ticker.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Dict[str, GetMainBalanceResponseValue]]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/main-account/balance",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "ticker": ticker,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, GetMainBalanceResponseValue],
                    parse_obj_as(
                        type_=typing.Dict[str, GetMainBalanceResponseValue],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_deposit_withdraw_history(
        self,
        *,
        request: str,
        nonce: str,
        transaction_method: typing.Optional[int] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        address: typing.Optional[str] = OMIT,
        memo: typing.Optional[str] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        unique_id: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        status: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetDepositWithdrawHistoryResponse]:
        """
        The endpoint retrieves the history of deposits and withdraws.

        **Deposit status codes:**
        - `Successful` - 3, 7
        - `Canceled` - 4, 9
        - `Unconfirmed by user` - 5
        - `Additional data required` - 21
        - `Uncredited` - 22
        - `Pending` - 15

        **Travel Rule Deposit check status codes:**
        - `Awaiting verification` - 27: The transaction has been frozen due to the lack of data required under the Travel Rule. The user is required to provide this data manually through the exchange interface.
        - `Confirmation in progress` - 28: The Travel Rule data provided by the user is currently being verified by WhiteBIT.

        ⚠️ Due to regulatory requirements in Turkey and [EU](/glossary#european-economic-area-eea), the system places every inbound crypto deposit on hold (frozen) until confirming the transaction's origin. The sender must provide certain details if the transaction is from another Virtual Asset Service Provider (VASP) or verify the address if from a self-hosted wallet. The system credits deposited funds to the account only after successful verification.

        **Withdraw status codes:**
        - `Pending` - 1, 2, 6, 10, 11, 12, 13, 14, 15, 16, 17
        - `Successful` - 3, 7
        - `Canceled` - 4
        - `Unconfirmed by user` - 5
        - `Additional data required` - 21
        - `Partially successful` - 18

        <Warning>
        Rate limit: 200 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        transaction_method : typing.Optional[int]
            Method. Example: **1** to display deposits / **2** to display withdraws. Do not send this parameter in order to receive both deposits and withdraws.

        ticker : typing.Optional[str]
            Currency's [ticker](/glossary#ticker). Example: BTC

        address : typing.Optional[str]
            Can be used for filtering transactions by specific address.

        memo : typing.Optional[str]
            Can be used for filtering transactions by specific [memo](/glossary#memodestination-tag)

        addresses : typing.Optional[typing.Sequence[str]]
            Can be used for filtering transactions by specific array of addresses.

        unique_id : typing.Optional[str]
            Can be used for filtering transactions by specific unique id

        limit : typing.Optional[int]
            LIMIT is a special clause used to limit records a particular query can return.

        offset : typing.Optional[int]
            Use the OFFSET clause to return entries starting from a particular line.

        status : typing.Optional[typing.Sequence[int]]
            Can be used for filtering transactions by status codes.

            ⚠️ Caution: Use this parameter with the appropriate `transactionMethod` and valid status codes for that method. See the endpoint description above for valid codes. Example: `"status": [3,7]`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetDepositWithdrawHistoryResponse]
            All validations succeeded and creating transaction is started
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/main-account/history",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "transactionMethod": transaction_method,
                "ticker": ticker,
                "address": address,
                "memo": memo,
                "addresses": addresses,
                "unique_id": unique_id,
                "limit": limit,
                "offset": offset,
                "status": status,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetDepositWithdrawHistoryResponse,
                    parse_obj_as(
                        type_=GetDepositWithdrawHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMainAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_main_balance(
        self,
        *,
        request: str,
        nonce: str,
        ticker: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Dict[str, GetMainBalanceResponseValue]]:
        """
        The endpoint retrieves the [main balance](/glossary#balance-main) by currency [ticker](/glossary#ticker) or all balances.

        <Warning>
          Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        ticker : typing.Optional[str]
            Currency's ticker.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Dict[str, GetMainBalanceResponseValue]]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/main-account/balance",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "ticker": ticker,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, GetMainBalanceResponseValue],
                    parse_obj_as(
                        type_=typing.Dict[str, GetMainBalanceResponseValue],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_deposit_withdraw_history(
        self,
        *,
        request: str,
        nonce: str,
        transaction_method: typing.Optional[int] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        address: typing.Optional[str] = OMIT,
        memo: typing.Optional[str] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        unique_id: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        status: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetDepositWithdrawHistoryResponse]:
        """
        The endpoint retrieves the history of deposits and withdraws.

        **Deposit status codes:**
        - `Successful` - 3, 7
        - `Canceled` - 4, 9
        - `Unconfirmed by user` - 5
        - `Additional data required` - 21
        - `Uncredited` - 22
        - `Pending` - 15

        **Travel Rule Deposit check status codes:**
        - `Awaiting verification` - 27: The transaction has been frozen due to the lack of data required under the Travel Rule. The user is required to provide this data manually through the exchange interface.
        - `Confirmation in progress` - 28: The Travel Rule data provided by the user is currently being verified by WhiteBIT.

        ⚠️ Due to regulatory requirements in Turkey and [EU](/glossary#european-economic-area-eea), the system places every inbound crypto deposit on hold (frozen) until confirming the transaction's origin. The sender must provide certain details if the transaction is from another Virtual Asset Service Provider (VASP) or verify the address if from a self-hosted wallet. The system credits deposited funds to the account only after successful verification.

        **Withdraw status codes:**
        - `Pending` - 1, 2, 6, 10, 11, 12, 13, 14, 15, 16, 17
        - `Successful` - 3, 7
        - `Canceled` - 4
        - `Unconfirmed by user` - 5
        - `Additional data required` - 21
        - `Partially successful` - 18

        <Warning>
        Rate limit: 200 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        Parameters
        ----------
        request : str
            Request signature

        nonce : str
            Unique request identifier

        transaction_method : typing.Optional[int]
            Method. Example: **1** to display deposits / **2** to display withdraws. Do not send this parameter in order to receive both deposits and withdraws.

        ticker : typing.Optional[str]
            Currency's [ticker](/glossary#ticker). Example: BTC

        address : typing.Optional[str]
            Can be used for filtering transactions by specific address.

        memo : typing.Optional[str]
            Can be used for filtering transactions by specific [memo](/glossary#memodestination-tag)

        addresses : typing.Optional[typing.Sequence[str]]
            Can be used for filtering transactions by specific array of addresses.

        unique_id : typing.Optional[str]
            Can be used for filtering transactions by specific unique id

        limit : typing.Optional[int]
            LIMIT is a special clause used to limit records a particular query can return.

        offset : typing.Optional[int]
            Use the OFFSET clause to return entries starting from a particular line.

        status : typing.Optional[typing.Sequence[int]]
            Can be used for filtering transactions by status codes.

            ⚠️ Caution: Use this parameter with the appropriate `transactionMethod` and valid status codes for that method. See the endpoint description above for valid codes. Example: `"status": [3,7]`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetDepositWithdrawHistoryResponse]
            All validations succeeded and creating transaction is started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/main-account/history",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "transactionMethod": transaction_method,
                "ticker": ticker,
                "address": address,
                "memo": memo,
                "addresses": addresses,
                "unique_id": unique_id,
                "limit": limit,
                "offset": offset,
                "status": status,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetDepositWithdrawHistoryResponse,
                    parse_obj_as(
                        type_=GetDepositWithdrawHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
