# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawMarketFeeClient, RawMarketFeeClient
from .types.get_market_fee_response import GetMarketFeeResponse


class MarketFeeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMarketFeeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMarketFeeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMarketFeeClient
        """
        return self._raw_client

    def get_market_fee(
        self, *, market: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetMarketFeeResponse:
        """
        Returns maker and taker fees for a specific market.

        The `maker` and `taker` fields represent spot trading fees. The `futures_maker` and `futures_taker` fields represent futures trading fees.

        The system calculates the effective futures fee as the lower value between the user-specific custom fee and the market-specific fee.

        When the market fee is lower than the assigned custom fee, the system returns the market fee.

        Example: If the custom futures taker fee equals `0.026` and the market fee equals `0.02`, the response returns `0.02`.

        Parameters
        ----------
        market : str
            Market to query.

            If the request includes the `market` parameter, the system returns fees for the specified market only.

            When fee values are identical across markets, the response contains identical values regardless of the specified market.

            Example: BTC_USDT

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMarketFeeResponse
            Successful response

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.market_fee.get_market_fee(market='BTC_USDT', )
        """
        _response = self._raw_client.get_market_fee(market=market, request_options=request_options)
        return _response.data


class AsyncMarketFeeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMarketFeeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMarketFeeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMarketFeeClient
        """
        return self._raw_client

    async def get_market_fee(
        self, *, market: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetMarketFeeResponse:
        """
        Returns maker and taker fees for a specific market.

        The `maker` and `taker` fields represent spot trading fees. The `futures_maker` and `futures_taker` fields represent futures trading fees.

        The system calculates the effective futures fee as the lower value between the user-specific custom fee and the market-specific fee.

        When the market fee is lower than the assigned custom fee, the system returns the market fee.

        Example: If the custom futures taker fee equals `0.026` and the market fee equals `0.02`, the response returns `0.02`.

        Parameters
        ----------
        market : str
            Market to query.

            If the request includes the `market` parameter, the system returns fees for the specified market only.

            When fee values are identical across markets, the response contains identical values regardless of the specified market.

            Example: BTC_USDT

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMarketFeeResponse
            Successful response

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.market_fee.get_market_fee(market='BTC_USDT', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_market_fee(market=market, request_options=request_options)
        return _response.data
