# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from .types.get_market_fee_response import GetMarketFeeResponse


class RawMarketFeeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_market_fee(
        self, *, market: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetMarketFeeResponse]:
        """
        Returns maker and taker fees for a specific market.

        The `maker` and `taker` fields represent spot trading fees. The `futures_maker` and `futures_taker` fields represent futures trading fees.

        The system calculates the effective futures fee as the lower value between the user-specific custom fee and the market-specific fee.

        When the market fee is lower than the assigned custom fee, the system returns the market fee.

        Example: If the custom futures taker fee equals `0.026` and the market fee equals `0.02`, the response returns `0.02`.

        Parameters
        ----------
        market : str
            Market to query.

            If the request includes the `market` parameter, the system returns fees for the specified market only.

            When fee values are identical across markets, the response contains identical values regardless of the specified market.

            Example: BTC_USDT

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetMarketFeeResponse]
            Successful response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/market/fee",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            params={
                "market": market,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetMarketFeeResponse,
                    parse_obj_as(
                        type_=GetMarketFeeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMarketFeeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_market_fee(
        self, *, market: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetMarketFeeResponse]:
        """
        Returns maker and taker fees for a specific market.

        The `maker` and `taker` fields represent spot trading fees. The `futures_maker` and `futures_taker` fields represent futures trading fees.

        The system calculates the effective futures fee as the lower value between the user-specific custom fee and the market-specific fee.

        When the market fee is lower than the assigned custom fee, the system returns the market fee.

        Example: If the custom futures taker fee equals `0.026` and the market fee equals `0.02`, the response returns `0.02`.

        Parameters
        ----------
        market : str
            Market to query.

            If the request includes the `market` parameter, the system returns fees for the specified market only.

            When fee values are identical across markets, the response contains identical values regardless of the specified market.

            Example: BTC_USDT

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetMarketFeeResponse]
            Successful response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/market/fee",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            params={
                "market": market,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetMarketFeeResponse,
                    parse_obj_as(
                        type_=GetMarketFeeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
