# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawTransferClient, RawTransferClient
from .types.transfer_between_balances_request_from import TransferBetweenBalancesRequestFrom
from .types.transfer_between_balances_request_method import TransferBetweenBalancesRequestMethod
from .types.transfer_between_balances_request_to import TransferBetweenBalancesRequestTo

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TransferClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTransferClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTransferClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTransferClient
        """
        return self._raw_client

    def between_balances(
        self,
        *,
        ticker: str,
        amount: str,
        request: str,
        nonce: str,
        method: typing.Optional[TransferBetweenBalancesRequestMethod] = OMIT,
        from_: typing.Optional[TransferBetweenBalancesRequestFrom] = OMIT,
        to: typing.Optional[TransferBetweenBalancesRequestTo] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Optional[typing.Any]]:
        """
        The endpoint transfers the specified amount between [main](/glossary#balance-main), [trade](/glossary#balance-spotbalance-trade) and [collateral](/glossary#balance-collateral) balances.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        <Note>
        Also, fiat currencies can't be transferred without KYC verification.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's [ticker](/glossary#ticker). Example: BTC

        amount : str
            Amount to transfer. Max [precision](/glossary#precision) = 8, value must be greater than zero and less than or equal to the available balance.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        method : typing.Optional[TransferBetweenBalancesRequestMethod]
            Transfer method.

            ⚠️ We highly recommend to use **from** and **to** fields, which provides more flexibility. This way will be deprecated in future.

            Example: **deposit** to transfer from [main](/glossary#balance-main) to [trade](/glossary#balance-spotbalance-trade) / **withdraw** to transfer from [trade](/glossary#balance-spotbalance-trade) balance to [main](/glossary#balance-main). For [collateral balances](/glossary#balance-collateral) use **collateral-deposit** to transfer from main to collateral and **collateral-withdraw** to transfer from collateral to main

            **Not required** if **from** and **to** are set.

        from_ : typing.Optional[TransferBetweenBalancesRequestFrom]
            Balance FROM which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)

            **Not required** if **method** is set.

        to : typing.Optional[TransferBetweenBalancesRequestTo]
            Balance TO which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)

            **Not required** if **method** is set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Optional[typing.Any]]
            All validations succeeded and creating transaction is started

        Examples
        --------
        from whitebit import WhitebitApi
        client = WhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        client.transfer.between_balances(method="deposit", ticker='XLM', amount='0.9', request='{{request}}', nonce='{{nonce}}', )
        """
        _response = self._raw_client.between_balances(
            ticker=ticker,
            amount=amount,
            request=request,
            nonce=nonce,
            method=method,
            from_=from_,
            to=to,
            request_options=request_options,
        )
        return _response.data


class AsyncTransferClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTransferClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTransferClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTransferClient
        """
        return self._raw_client

    async def between_balances(
        self,
        *,
        ticker: str,
        amount: str,
        request: str,
        nonce: str,
        method: typing.Optional[TransferBetweenBalancesRequestMethod] = OMIT,
        from_: typing.Optional[TransferBetweenBalancesRequestFrom] = OMIT,
        to: typing.Optional[TransferBetweenBalancesRequestTo] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Optional[typing.Any]]:
        """
        The endpoint transfers the specified amount between [main](/glossary#balance-main), [trade](/glossary#balance-spotbalance-trade) and [collateral](/glossary#balance-collateral) balances.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        <Note>
        Also, fiat currencies can't be transferred without KYC verification.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's [ticker](/glossary#ticker). Example: BTC

        amount : str
            Amount to transfer. Max [precision](/glossary#precision) = 8, value must be greater than zero and less than or equal to the available balance.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        method : typing.Optional[TransferBetweenBalancesRequestMethod]
            Transfer method.

            ⚠️ We highly recommend to use **from** and **to** fields, which provides more flexibility. This way will be deprecated in future.

            Example: **deposit** to transfer from [main](/glossary#balance-main) to [trade](/glossary#balance-spotbalance-trade) / **withdraw** to transfer from [trade](/glossary#balance-spotbalance-trade) balance to [main](/glossary#balance-main). For [collateral balances](/glossary#balance-collateral) use **collateral-deposit** to transfer from main to collateral and **collateral-withdraw** to transfer from collateral to main

            **Not required** if **from** and **to** are set.

        from_ : typing.Optional[TransferBetweenBalancesRequestFrom]
            Balance FROM which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)

            **Not required** if **method** is set.

        to : typing.Optional[TransferBetweenBalancesRequestTo]
            Balance TO which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)

            **Not required** if **method** is set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Optional[typing.Any]]
            All validations succeeded and creating transaction is started

        Examples
        --------
        from whitebit import AsyncWhitebitApi
        import asyncio
        client = AsyncWhitebitApi(txc_apikey="YOUR_TXC_APIKEY", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.transfer.between_balances(method="deposit", ticker='XLM', amount='0.9', request='{{request}}', nonce='{{nonce}}', )
        asyncio.run(main())
        """
        _response = await self._raw_client.between_balances(
            ticker=ticker,
            amount=amount,
            request=request,
            nonce=nonce,
            method=method,
            from_=from_,
            to=to,
            request_options=request_options,
        )
        return _response.data
