# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from .types.transfer_between_balances_request_from import TransferBetweenBalancesRequestFrom
from .types.transfer_between_balances_request_method import TransferBetweenBalancesRequestMethod
from .types.transfer_between_balances_request_to import TransferBetweenBalancesRequestTo

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTransferClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def between_balances(
        self,
        *,
        ticker: str,
        amount: str,
        request: str,
        nonce: str,
        method: typing.Optional[TransferBetweenBalancesRequestMethod] = OMIT,
        from_: typing.Optional[TransferBetweenBalancesRequestFrom] = OMIT,
        to: typing.Optional[TransferBetweenBalancesRequestTo] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[typing.Optional[typing.Any]]]:
        """
        The endpoint transfers the specified amount between [main](/glossary#balance-main), [trade](/glossary#balance-spotbalance-trade) and [collateral](/glossary#balance-collateral) balances.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        <Note>
        Also, fiat currencies can't be transferred without KYC verification.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's [ticker](/glossary#ticker). Example: BTC

        amount : str
            Amount to transfer. Max [precision](/glossary#precision) = 8, value must be greater than zero and less than or equal to the available balance.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        method : typing.Optional[TransferBetweenBalancesRequestMethod]
            Transfer method.

            ⚠️ We highly recommend to use **from** and **to** fields, which provides more flexibility. This way will be deprecated in future.

            Example: **deposit** to transfer from [main](/glossary#balance-main) to [trade](/glossary#balance-spotbalance-trade) / **withdraw** to transfer from [trade](/glossary#balance-spotbalance-trade) balance to [main](/glossary#balance-main). For [collateral balances](/glossary#balance-collateral) use **collateral-deposit** to transfer from main to collateral and **collateral-withdraw** to transfer from collateral to main

            **Not required** if **from** and **to** are set.

        from_ : typing.Optional[TransferBetweenBalancesRequestFrom]
            Balance FROM which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)

            **Not required** if **method** is set.

        to : typing.Optional[TransferBetweenBalancesRequestTo]
            Balance TO which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)

            **Not required** if **method** is set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[typing.Optional[typing.Any]]]
            All validations succeeded and creating transaction is started
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v4/main-account/transfer",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "method": method,
                "from": from_,
                "to": to,
                "ticker": ticker,
                "amount": amount,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[typing.Optional[typing.Any]],
                    parse_obj_as(
                        type_=typing.List[typing.Optional[typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTransferClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def between_balances(
        self,
        *,
        ticker: str,
        amount: str,
        request: str,
        nonce: str,
        method: typing.Optional[TransferBetweenBalancesRequestMethod] = OMIT,
        from_: typing.Optional[TransferBetweenBalancesRequestFrom] = OMIT,
        to: typing.Optional[TransferBetweenBalancesRequestTo] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[typing.Optional[typing.Any]]]:
        """
        The endpoint transfers the specified amount between [main](/glossary#balance-main), [trade](/glossary#balance-spotbalance-trade) and [collateral](/glossary#balance-collateral) balances.

        <Warning>
        Rate limit: 1000 requests/10 sec.
        </Warning>

        <Note>
        The API does not cache the response.
        </Note>

        <Note>
        Also, fiat currencies can't be transferred without KYC verification.
        </Note>

        Parameters
        ----------
        ticker : str
            Currency's [ticker](/glossary#ticker). Example: BTC

        amount : str
            Amount to transfer. Max [precision](/glossary#precision) = 8, value must be greater than zero and less than or equal to the available balance.

        request : str
            Request signature

        nonce : str
            Unique request identifier

        method : typing.Optional[TransferBetweenBalancesRequestMethod]
            Transfer method.

            ⚠️ We highly recommend to use **from** and **to** fields, which provides more flexibility. This way will be deprecated in future.

            Example: **deposit** to transfer from [main](/glossary#balance-main) to [trade](/glossary#balance-spotbalance-trade) / **withdraw** to transfer from [trade](/glossary#balance-spotbalance-trade) balance to [main](/glossary#balance-main). For [collateral balances](/glossary#balance-collateral) use **collateral-deposit** to transfer from main to collateral and **collateral-withdraw** to transfer from collateral to main

            **Not required** if **from** and **to** are set.

        from_ : typing.Optional[TransferBetweenBalancesRequestFrom]
            Balance FROM which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)

            **Not required** if **method** is set.

        to : typing.Optional[TransferBetweenBalancesRequestTo]
            Balance TO which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)

            **Not required** if **method** is set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[typing.Optional[typing.Any]]]
            All validations succeeded and creating transaction is started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v4/main-account/transfer",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "method": method,
                "from": from_,
                "to": to,
                "ticker": ticker,
                "amount": amount,
                "request": request,
                "nonce": nonce,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[typing.Optional[typing.Any]],
                    parse_obj_as(
                        type_=typing.List[typing.Optional[typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
