# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PostOauth2RefreshTokenResponseData(UniversalBaseModel):
    access_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The new access token for API requests
    """

    expires_in: typing.Optional[int] = pydantic.Field(default=None)
    """
    Token expiration time in seconds
    """

    refresh_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    New refresh token
    """

    scope: typing.Optional[str] = pydantic.Field(default=None)
    """
    Comma-separated list of granted scopes
    """

    token_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type of the token
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
